/**
 * Feed data types and mock data source.
 * This file is the single data source for the feed — swap the mock array
 * with a fetch call when the API is ready.
 */

export type FeedPost = {
  id: string;
  authorId: string;
  authorName: string;
  authorHandle: string;
  authorImage: string;
  isFollowingAuthor: boolean;
  createdAt: string;
  bodyText: string;
  bodyLanguage: string;
  isTranslated: boolean;
  backgroundKey: string;
  imageUrl?: string;
  imageWidth?: number;
  imageHeight?: number;
  likeCount: number;
  commentCount: number;
  likedByMe: boolean;
};

export const MOCK_FEED_POSTS: FeedPost[] = [
  {
    id: "post-1",
    authorId: "user-1",
    authorName: "지민",
    authorHandle: "jimin_life",
    authorImage: "",
    isFollowingAuthor: false,
    createdAt: "2026-09-25T12:00:00Z",
    bodyText: "오늘 하루도 수고했어요 🌟\n내일은 더 좋은 일이 생길 거예요.",
    bodyLanguage: "ko",
    isTranslated: false,
    backgroundKey: "sunset-orange",
    likeCount: 42,
    commentCount: 5,
    likedByMe: false,
  },
  {
    id: "post-2",
    authorId: "user-2",
    authorName: "Alex Chen",
    authorHandle: "alexc",
    authorImage: "",
    isFollowingAuthor: true,
    createdAt: "2026-09-25T10:30:00Z",
    bodyText:
      "Just landed in Tokyo! The city lights are absolutely breathtaking. Can't wait to explore Shibuya tonight. 🗼",
    bodyLanguage: "en",
    isTranslated: false,
    backgroundKey: "ocean-blue",
    likeCount: 128,
    commentCount: 23,
    likedByMe: true,
  },
  {
    id: "post-3",
    authorId: "user-3",
    authorName: "田中太郎",
    authorHandle: "tanaka_t",
    authorImage: "",
    isFollowingAuthor: false,
    createdAt: "2026-09-25T09:15:00Z",
    bodyText: "今日のランチは最高だった！新しいラーメン屋を見つけた 🍜",
    bodyLanguage: "ja",
    isTranslated: false,
    backgroundKey: "golden-hour",
    likeCount: 67,
    commentCount: 8,
    likedByMe: false,
  },
  {
    id: "post-4",
    authorId: "user-4",
    authorName: "서연",
    authorHandle: "seoyeon_art",
    authorImage: "",
    isFollowingAuthor: true,
    createdAt: "2026-09-24T22:00:00Z",
    bodyText:
      "그림을 그리다 보면 시간이 어떻게 가는지 모르겠어요. 새벽 3시까지 작업했는데 눈 떠보니 아침이었다는... 오늘도 열심히 그려봅니다 🎨",
    bodyLanguage: "ko",
    isTranslated: false,
    backgroundKey: "lavender-mist",
    likeCount: 203,
    commentCount: 31,
    likedByMe: false,
  },
  {
    id: "post-5",
    authorId: "user-5",
    authorName: "Maria Garcia",
    authorHandle: "maria.g",
    authorImage: "",
    isFollowingAuthor: false,
    createdAt: "2026-09-24T18:45:00Z",
    bodyText: "Life is short. Eat dessert first. 🍰",
    bodyLanguage: "en",
    isTranslated: false,
    backgroundKey: "dusty-rose",
    likeCount: 89,
    commentCount: 12,
    likedByMe: true,
  },
  {
    id: "post-6",
    authorId: "user-6",
    authorName: "현우",
    authorHandle: "hyunwoo_dev",
    authorImage: "",
    isFollowingAuthor: false,
    createdAt: "2026-09-24T15:30:00Z",
    bodyText: "코딩하다가 발견한 버그를 3시간 만에 고쳤다. 알고 보니 세미콜론 하나... 😅",
    bodyLanguage: "ko",
    isTranslated: false,
    backgroundKey: "soft-navy",
    likeCount: 156,
    commentCount: 42,
    likedByMe: false,
  },
  {
    id: "post-7",
    authorId: "user-7",
    authorName: "Yuki Sato",
    authorHandle: "yuki.s",
    authorImage: "",
    isFollowingAuthor: true,
    createdAt: "2026-09-24T12:00:00Z",
    bodyText:
      "桜の季節が待ち遠しい。去年撮った写真を見返していたら、もう一度あの場所に行きたくなった 🌸",
    bodyLanguage: "ja",
    isTranslated: false,
    backgroundKey: "aurora-green",
    likeCount: 94,
    commentCount: 7,
    likedByMe: false,
  },
  {
    id: "post-8",
    authorId: "user-8",
    authorName: "민수",
    authorHandle: "minsu.k",
    authorImage: "",
    isFollowingAuthor: false,
    createdAt: "2026-09-24T08:00:00Z",
    bodyText: "아침 러닝 5km 완료! 🏃‍♂️ 오늘도 건강한 하루 시작.",
    bodyLanguage: "ko",
    isTranslated: false,
    backgroundKey: "mint-green",
    likeCount: 33,
    commentCount: 2,
    likedByMe: false,
  },
  {
    id: "post-9",
    authorId: "user-9",
    authorName: "소이",
    authorHandle: "soi.writer",
    authorImage: "",
    isFollowingAuthor: false,
    createdAt: "2026-09-23T20:00:00Z",
    bodyText:
      "오늘은 오랫동안 미뤄둔 일기를 쓰기 시작했어요.\n\n한 줄 한 줄 적다 보니, 잊고 있었던 감정들이 떠올라서 꽤 놀랐습니다. 예전에 좋아했던 카페가 문을 닫았다는 소식을 듣고 괜히 마음이 허전했던 날, 비 오는 오후에 창가에서 멍하니 앉아 있었던 순간들.\n\n사소한 일상이라고 생각했는데, 적어놓으니 하나하나가 소중한 기억이 되더라고요. 누군가에게는 별것 아닌 이야기겠지만, 저에게는 나를 이해하는 시간이었어요.\n\n일기 쓰기를 추천합니다. 하루에 한 줄이라도. 나중에 돌아보면 그때의 나를 만날 수 있어요 📝\n\n그리고 또 하나, 글을 쓰면서 깨달은 건 완벽하지 않아도 괜찮다는 거예요. 맞춤법이 좀 틀리면 어때요. 문장이 좀 어색하면 어때요. 중요한 건 내 마음을 솔직하게 꺼내놓는 거니까요.\n\n오늘 밤, 여러분도 잠들기 전에 한 줄이라도 적어보세요. 오늘 가장 기억에 남는 한 가지를요. 그게 뭐든 괜찮아요.",
    bodyLanguage: "ko",
    isTranslated: false,
    backgroundKey: "warm-cream",
    likeCount: 312,
    commentCount: 47,
    likedByMe: false,
  },
  {
    id: "post-10",
    authorId: "user-10",
    authorName: "James Park",
    authorHandle: "jamespark",
    authorImage: "",
    isFollowingAuthor: true,
    createdAt: "2026-09-23T14:00:00Z",
    bodyText: "Sunset at the beach. No filter needed. 🌅",
    bodyLanguage: "en",
    isTranslated: false,
    backgroundKey: "golden-hour",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=800&fit=crop",
    imageWidth: 600,
    imageHeight: 800,
    likeCount: 445,
    commentCount: 56,
    likedByMe: false,
  },
  {
    id: "post-11",
    authorId: "user-11",
    authorName: "은서",
    authorHandle: "eunseo.photo",
    authorImage: "",
    isFollowingAuthor: false,
    createdAt: "2026-09-22T19:30:00Z",
    bodyText: "서울의 야경은 언제 봐도 아름다워요 ✨\n한강 다리 위에서 찍었는데 생각보다 잘 나왔어요.",
    bodyLanguage: "ko",
    isTranslated: false,
    backgroundKey: "midnight-purple",
    imageUrl: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=600&h=800&fit=crop",
    imageWidth: 600,
    imageHeight: 800,
    likeCount: 189,
    commentCount: 22,
    likedByMe: true,
  },
  {
    id: "post-12",
    authorId: "user-12",
    authorName: "하진",
    authorHandle: "hajin.0",
    authorImage: "",
    isFollowingAuthor: false,
    createdAt: "2026-09-22T10:00:00Z",
    bodyText: "☀️",
    bodyLanguage: "ko",
    isTranslated: false,
    backgroundKey: "paper-texture",
    likeCount: 0,
    commentCount: 0,
    likedByMe: false,
  },
];
