import { resolveLegalDocumentLocale, resolveSupportedLocaleTag, type LegalDocumentLocale } from '@/i18n/config'

/**
 * Compose-surface copy added with the posting-feed gap fixes (busy publish,
 * failed-publish preservation, edit conflicts, restore failures, paging,
 * photo decode failures). Lives beside the compose components so the shared
 * `@/i18n/compose-copy` module stays untouched; same 15 primary UI locales and
 * the same polite register as that module.
 */
export type ComposeGapCopy = {
  /** A second publish while one is still uploading: blocked, kept on screen + in drafts. */
  publishBusy: string
  /** Failed publish whose body was saved as a draft. */
  bannerFailedSavedDraft: string
  /** Dismissing a failed publish that could NOT be saved as a draft. */
  discardFailedPrompt: string
  discardFailedConfirm: string
  /** Autosave failed (network); the text stays on screen. */
  draftSaveFailed: string
  /** PATCH answered 409 — someone edited the post elsewhere. */
  editConflict: string
  editReload: string
  editSaveFailed: string
  restoreFailed: string
  restoreExpired: string
  unhideFailed: string
  loadMore: string
  /** The picked photo could not be read (decode failure; may be a denied permission). */
  photoLoadFailed: string
  /** HEIC/HEIF this browser cannot decode. */
  photoHeicUnsupported: string
}

const copy: Record<LegalDocumentLocale, ComposeGapCopy> = {
  ko: {
    publishBusy: '앞선 글을 게시하는 중입니다. 이 글은 임시저장에 보관했으니 끝난 뒤 다시 게시해 주세요.',
    bannerFailedSavedDraft: '게시하지 못했습니다. 글은 임시저장에 보관했습니다.',
    discardFailedPrompt: '게시하지 못한 글을 버릴까요? 내용이 사라집니다.',
    discardFailedConfirm: '버리기',
    draftSaveFailed: '임시저장하지 못했습니다. 입력한 내용은 화면에 남아 있습니다.',
    editConflict: '다른 곳에서 이 글이 수정되었습니다. 다시 불러온 뒤 수정해 주세요.',
    editReload: '다시 불러오기',
    editSaveFailed: '저장하지 못했습니다. 다시 시도해 주세요.',
    restoreFailed: '복원하지 못했습니다. 잠시 후 다시 시도해 주세요.',
    restoreExpired: '30일이 지나 복원할 수 없습니다.',
    unhideFailed: '숨김을 해제하지 못했습니다. 잠시 후 다시 시도해 주세요.',
    loadMore: '더 보기',
    photoLoadFailed: '사진을 불러오지 못했습니다. 사진 접근 권한을 거부했다면 설정에서 허용해 주세요.',
    photoHeicUnsupported: '이 기기에서는 HEIC 사진을 열 수 없습니다. JPG로 저장한 사진을 골라 주세요.',
  },
  en: {
    publishBusy: 'Your previous post is still posting. This one is saved in drafts — post it again when that finishes.',
    bannerFailedSavedDraft: 'Couldn’t post. Your post is saved in drafts.',
    discardFailedPrompt: 'Discard the post that failed? Its content will be lost.',
    discardFailedConfirm: 'Discard',
    draftSaveFailed: 'Couldn’t save the draft. What you wrote is still here.',
    editConflict: 'This post was edited somewhere else. Reload it, then edit again.',
    editReload: 'Reload',
    editSaveFailed: 'Couldn’t save. Please try again.',
    restoreFailed: 'Couldn’t restore. Please try again shortly.',
    restoreExpired: 'More than 30 days have passed, so it can’t be restored.',
    unhideFailed: 'Couldn’t unhide. Please try again shortly.',
    loadMore: 'Load more',
    photoLoadFailed: 'Couldn’t open the photo. If you denied photo access, allow it in Settings.',
    photoHeicUnsupported: 'HEIC photos can’t be opened on this device. Choose a photo saved as JPG.',
  },
  ja: {
    publishBusy: '前の投稿を送信中です。この投稿は下書きに保存したので、完了後にもう一度投稿してください。',
    bannerFailedSavedDraft: '投稿できませんでした。下書きに保存しました。',
    discardFailedPrompt: '投稿できなかった内容を破棄しますか？内容は失われます。',
    discardFailedConfirm: '破棄',
    draftSaveFailed: '下書きを保存できませんでした。入力内容は画面に残っています。',
    editConflict: 'この投稿は別の場所で編集されました。再読み込みしてから編集してください。',
    editReload: '再読み込み',
    editSaveFailed: '保存できませんでした。もう一度お試しください。',
    restoreFailed: '復元できませんでした。しばらくしてからお試しください。',
    restoreExpired: '30日を過ぎたため復元できません。',
    unhideFailed: '非表示を解除できませんでした。しばらくしてからお試しください。',
    loadMore: 'もっと見る',
    photoLoadFailed: '写真を開けませんでした。写真へのアクセスを拒否した場合は設定で許可してください。',
    photoHeicUnsupported: 'この端末ではHEIC写真を開けません。JPGで保存した写真を選んでください。',
  },
  'zh-CN': {
    publishBusy: '上一条帖子仍在发布中。这条已存入草稿，完成后请再次发布。',
    bannerFailedSavedDraft: '发布失败。帖子已存入草稿。',
    discardFailedPrompt: '要放弃发布失败的帖子吗？内容将会丢失。',
    discardFailedConfirm: '放弃',
    draftSaveFailed: '草稿未能保存。你写的内容仍保留在此。',
    editConflict: '这条帖子已在其他地方被修改。请重新加载后再编辑。',
    editReload: '重新加载',
    editSaveFailed: '保存失败，请重试。',
    restoreFailed: '恢复失败，请稍后重试。',
    restoreExpired: '已超过30天，无法恢复。',
    unhideFailed: '无法取消隐藏，请稍后重试。',
    loadMore: '加载更多',
    photoLoadFailed: '无法打开照片。如果你拒绝了照片访问权限，请在设置中允许。',
    photoHeicUnsupported: '此设备无法打开HEIC照片。请选择保存为JPG的照片。',
  },
  'zh-TW': {
    publishBusy: '上一則貼文仍在發布中。這則已存入草稿，完成後請再次發布。',
    bannerFailedSavedDraft: '發布失敗。貼文已存入草稿。',
    discardFailedPrompt: '要捨棄發布失敗的貼文嗎？內容將會遺失。',
    discardFailedConfirm: '捨棄',
    draftSaveFailed: '草稿無法儲存。你寫的內容仍保留在此。',
    editConflict: '這則貼文已在其他地方被修改。請重新載入後再編輯。',
    editReload: '重新載入',
    editSaveFailed: '儲存失敗，請再試一次。',
    restoreFailed: '無法還原，請稍後再試。',
    restoreExpired: '已超過30天，無法還原。',
    unhideFailed: '無法取消隱藏，請稍後再試。',
    loadMore: '載入更多',
    photoLoadFailed: '無法開啟照片。如果你拒絕了照片存取權限，請在設定中允許。',
    photoHeicUnsupported: '此裝置無法開啟HEIC照片。請選擇儲存為JPG的照片。',
  },
  fr: {
    publishBusy: 'Votre publication précédente est en cours. Celle-ci est gardée en brouillon : republiez-la ensuite.',
    bannerFailedSavedDraft: 'Échec de la publication. Elle est gardée en brouillon.',
    discardFailedPrompt: 'Abandonner la publication échouée ? Son contenu sera perdu.',
    discardFailedConfirm: 'Abandonner',
    draftSaveFailed: 'Brouillon non enregistré. Votre texte est toujours là.',
    editConflict: 'Cette publication a été modifiée ailleurs. Rechargez-la, puis modifiez-la.',
    editReload: 'Recharger',
    editSaveFailed: 'Enregistrement impossible. Réessayez.',
    restoreFailed: 'Restauration impossible. Réessayez plus tard.',
    restoreExpired: 'Plus de 30 jours sont passés : restauration impossible.',
    unhideFailed: 'Impossible de réafficher. Réessayez plus tard.',
    loadMore: 'Voir plus',
    photoLoadFailed: 'Impossible d’ouvrir la photo. Si vous avez refusé l’accès aux photos, autorisez-le dans les réglages.',
    photoHeicUnsupported: 'Les photos HEIC ne s’ouvrent pas sur cet appareil. Choisissez une photo en JPG.',
  },
  de: {
    publishBusy: 'Dein vorheriger Beitrag wird noch gepostet. Dieser ist als Entwurf gespeichert – poste ihn danach erneut.',
    bannerFailedSavedDraft: 'Posten fehlgeschlagen. Als Entwurf gespeichert.',
    discardFailedPrompt: 'Fehlgeschlagenen Beitrag verwerfen? Der Inhalt geht verloren.',
    discardFailedConfirm: 'Verwerfen',
    draftSaveFailed: 'Entwurf nicht gespeichert. Dein Text ist noch da.',
    editConflict: 'Der Beitrag wurde woanders bearbeitet. Neu laden und dann bearbeiten.',
    editReload: 'Neu laden',
    editSaveFailed: 'Speichern fehlgeschlagen. Bitte erneut versuchen.',
    restoreFailed: 'Wiederherstellen fehlgeschlagen. Bitte später erneut versuchen.',
    restoreExpired: 'Über 30 Tage vergangen – Wiederherstellen nicht möglich.',
    unhideFailed: 'Einblenden fehlgeschlagen. Bitte später erneut versuchen.',
    loadMore: 'Mehr laden',
    photoLoadFailed: 'Foto konnte nicht geöffnet werden. Falls du den Fotozugriff abgelehnt hast, erlaube ihn in den Einstellungen.',
    photoHeicUnsupported: 'HEIC-Fotos lassen sich hier nicht öffnen. Wähle ein als JPG gespeichertes Foto.',
  },
  es: {
    publishBusy: 'Tu publicación anterior aún se está publicando. Esta quedó en borradores: publícala al terminar.',
    bannerFailedSavedDraft: 'No se pudo publicar. Quedó guardada en borradores.',
    discardFailedPrompt: '¿Descartar la publicación fallida? Se perderá su contenido.',
    discardFailedConfirm: 'Descartar',
    draftSaveFailed: 'No se pudo guardar el borrador. Lo que escribiste sigue aquí.',
    editConflict: 'Esta publicación se editó en otro lugar. Recárgala y vuelve a editarla.',
    editReload: 'Recargar',
    editSaveFailed: 'No se pudo guardar. Inténtalo de nuevo.',
    restoreFailed: 'No se pudo restaurar. Inténtalo en un momento.',
    restoreExpired: 'Pasaron más de 30 días, ya no se puede restaurar.',
    unhideFailed: 'No se pudo mostrar de nuevo. Inténtalo en un momento.',
    loadMore: 'Ver más',
    photoLoadFailed: 'No se pudo abrir la foto. Si negaste el acceso a fotos, permítelo en Ajustes.',
    photoHeicUnsupported: 'Las fotos HEIC no se abren en este dispositivo. Elige una foto en JPG.',
  },
  pt: {
    publishBusy: 'Sua publicação anterior ainda está sendo enviada. Esta ficou nos rascunhos: publique de novo depois.',
    bannerFailedSavedDraft: 'Não foi possível publicar. Ficou salva nos rascunhos.',
    discardFailedPrompt: 'Descartar a publicação que falhou? O conteúdo será perdido.',
    discardFailedConfirm: 'Descartar',
    draftSaveFailed: 'Não foi possível salvar o rascunho. O que você escreveu continua aqui.',
    editConflict: 'Esta publicação foi editada em outro lugar. Recarregue e edite de novo.',
    editReload: 'Recarregar',
    editSaveFailed: 'Não foi possível salvar. Tente novamente.',
    restoreFailed: 'Não foi possível restaurar. Tente daqui a pouco.',
    restoreExpired: 'Já se passaram mais de 30 dias, não dá para restaurar.',
    unhideFailed: 'Não foi possível reexibir. Tente daqui a pouco.',
    loadMore: 'Ver mais',
    photoLoadFailed: 'Não foi possível abrir a foto. Se você negou o acesso às fotos, permita nos Ajustes.',
    photoHeicUnsupported: 'Fotos HEIC não abrem neste aparelho. Escolha uma foto em JPG.',
  },
  it: {
    publishBusy: 'Il post precedente è ancora in pubblicazione. Questo è nelle bozze: pubblicalo dopo.',
    bannerFailedSavedDraft: 'Pubblicazione non riuscita. Il post è nelle bozze.',
    discardFailedPrompt: 'Scartare il post non pubblicato? Il contenuto andrà perso.',
    discardFailedConfirm: 'Scarta',
    draftSaveFailed: 'Bozza non salvata. Il tuo testo è ancora qui.',
    editConflict: 'Questo post è stato modificato altrove. Ricaricalo e poi modificalo.',
    editReload: 'Ricarica',
    editSaveFailed: 'Salvataggio non riuscito. Riprova.',
    restoreFailed: 'Ripristino non riuscito. Riprova tra poco.',
    restoreExpired: 'Sono passati più di 30 giorni: non si può ripristinare.',
    unhideFailed: 'Impossibile mostrare di nuovo. Riprova tra poco.',
    loadMore: 'Carica altri',
    photoLoadFailed: 'Impossibile aprire la foto. Se hai negato l’accesso alle foto, consentilo nelle Impostazioni.',
    photoHeicUnsupported: 'Le foto HEIC non si aprono su questo dispositivo. Scegli una foto in JPG.',
  },
  ru: {
    publishBusy: 'Предыдущий пост ещё публикуется. Этот сохранён в черновиках — опубликуйте его после.',
    bannerFailedSavedDraft: 'Не удалось опубликовать. Пост сохранён в черновиках.',
    discardFailedPrompt: 'Удалить неопубликованный пост? Содержимое будет потеряно.',
    discardFailedConfirm: 'Удалить',
    draftSaveFailed: 'Черновик не сохранён. Ваш текст остался на экране.',
    editConflict: 'Пост был изменён в другом месте. Обновите его и отредактируйте снова.',
    editReload: 'Обновить',
    editSaveFailed: 'Не удалось сохранить. Попробуйте ещё раз.',
    restoreFailed: 'Не удалось восстановить. Попробуйте чуть позже.',
    restoreExpired: 'Прошло больше 30 дней — восстановить нельзя.',
    unhideFailed: 'Не удалось вернуть пост. Попробуйте чуть позже.',
    loadMore: 'Показать ещё',
    photoLoadFailed: 'Не удалось открыть фото. Если вы запретили доступ к фото, разрешите его в настройках.',
    photoHeicUnsupported: 'Фото HEIC не открываются на этом устройстве. Выберите фото в формате JPG.',
  },
  ar: {
    publishBusy: 'منشورك السابق لا يزال قيد النشر. حُفظ هذا في المسودات، فانشره مجددًا بعد الانتهاء.',
    bannerFailedSavedDraft: 'تعذّر النشر. حُفظ المنشور في المسودات.',
    discardFailedPrompt: 'هل تريد تجاهل المنشور الذي فشل؟ سيُفقد محتواه.',
    discardFailedConfirm: 'تجاهل',
    draftSaveFailed: 'تعذّر حفظ المسودة. ما كتبته لا يزال هنا.',
    editConflict: 'عُدّل هذا المنشور في مكان آخر. أعد تحميله ثم عدّله.',
    editReload: 'إعادة التحميل',
    editSaveFailed: 'تعذّر الحفظ. حاول مرة أخرى.',
    restoreFailed: 'تعذّرت الاستعادة. حاول بعد قليل.',
    restoreExpired: 'مرّ أكثر من 30 يومًا، فلا يمكن الاستعادة.',
    unhideFailed: 'تعذّر إلغاء الإخفاء. حاول بعد قليل.',
    loadMore: 'عرض المزيد',
    photoLoadFailed: 'تعذّر فتح الصورة. إذا رفضت الوصول إلى الصور، فاسمح به من الإعدادات.',
    photoHeicUnsupported: 'لا يمكن فتح صور HEIC على هذا الجهاز. اختر صورة محفوظة بصيغة JPG.',
  },
  hi: {
    publishBusy: 'आपकी पिछली पोस्ट अभी पोस्ट हो रही है। यह ड्राफ़्ट में सहेजी गई है, उसके बाद इसे फिर पोस्ट करें।',
    bannerFailedSavedDraft: 'पोस्ट नहीं हो सकी। यह ड्राफ़्ट में सहेजी गई है।',
    discardFailedPrompt: 'विफल पोस्ट हटाएँ? उसकी सामग्री खो जाएगी।',
    discardFailedConfirm: 'हटाएँ',
    draftSaveFailed: 'ड्राफ़्ट सहेजा नहीं जा सका। आपने जो लिखा वह अभी यहीं है।',
    editConflict: 'यह पोस्ट कहीं और बदली गई है। इसे फिर से लोड करके संपादित करें।',
    editReload: 'फिर से लोड करें',
    editSaveFailed: 'सहेजा नहीं जा सका। फिर से कोशिश करें।',
    restoreFailed: 'बहाल नहीं हो सका। थोड़ी देर बाद कोशिश करें।',
    restoreExpired: '30 दिन बीत गए हैं, इसलिए बहाल नहीं किया जा सकता।',
    unhideFailed: 'छिपाना हटाया नहीं जा सका। थोड़ी देर बाद कोशिश करें।',
    loadMore: 'और देखें',
    photoLoadFailed: 'फ़ोटो नहीं खुल सकी। अगर आपने फ़ोटो की अनुमति नहीं दी थी, तो सेटिंग्स में दें।',
    photoHeicUnsupported: 'इस डिवाइस पर HEIC फ़ोटो नहीं खुलतीं। JPG में सहेजी गई फ़ोटो चुनें।',
  },
  th: {
    publishBusy: 'โพสต์ก่อนหน้ายังโพสต์อยู่ โพสต์นี้บันทึกไว้ในฉบับร่างแล้ว โพสต์อีกครั้งเมื่อเสร็จ',
    bannerFailedSavedDraft: 'โพสต์ไม่สำเร็จ บันทึกไว้ในฉบับร่างแล้ว',
    discardFailedPrompt: 'ทิ้งโพสต์ที่โพสต์ไม่สำเร็จไหม เนื้อหาจะหายไป',
    discardFailedConfirm: 'ทิ้ง',
    draftSaveFailed: 'บันทึกฉบับร่างไม่ได้ ข้อความที่เขียนยังอยู่ที่นี่',
    editConflict: 'โพสต์นี้ถูกแก้ไขจากที่อื่น โหลดใหม่แล้วแก้ไขอีกครั้ง',
    editReload: 'โหลดใหม่',
    editSaveFailed: 'บันทึกไม่ได้ โปรดลองอีกครั้ง',
    restoreFailed: 'กู้คืนไม่ได้ โปรดลองอีกครั้งภายหลัง',
    restoreExpired: 'เกิน 30 วันแล้ว จึงกู้คืนไม่ได้',
    unhideFailed: 'เลิกซ่อนไม่ได้ โปรดลองอีกครั้งภายหลัง',
    loadMore: 'ดูเพิ่มเติม',
    photoLoadFailed: 'เปิดรูปไม่ได้ หากคุณปฏิเสธการเข้าถึงรูปภาพ โปรดอนุญาตในการตั้งค่า',
    photoHeicUnsupported: 'อุปกรณ์นี้เปิดรูป HEIC ไม่ได้ โปรดเลือกรูปที่บันทึกเป็น JPG',
  },
  vi: {
    publishBusy: 'Bài trước vẫn đang được đăng. Bài này đã lưu vào bản nháp, hãy đăng lại khi xong.',
    bannerFailedSavedDraft: 'Không đăng được. Bài đã được lưu vào bản nháp.',
    discardFailedPrompt: 'Bỏ bài đăng không thành công? Nội dung sẽ bị mất.',
    discardFailedConfirm: 'Bỏ',
    draftSaveFailed: 'Không lưu được bản nháp. Nội dung bạn viết vẫn còn ở đây.',
    editConflict: 'Bài này đã được sửa ở nơi khác. Hãy tải lại rồi sửa tiếp.',
    editReload: 'Tải lại',
    editSaveFailed: 'Không lưu được. Vui lòng thử lại.',
    restoreFailed: 'Không khôi phục được. Vui lòng thử lại sau.',
    restoreExpired: 'Đã quá 30 ngày nên không thể khôi phục.',
    unhideFailed: 'Không bỏ ẩn được. Vui lòng thử lại sau.',
    loadMore: 'Xem thêm',
    photoLoadFailed: 'Không mở được ảnh. Nếu bạn đã từ chối quyền truy cập ảnh, hãy cho phép trong Cài đặt.',
    photoHeicUnsupported: 'Thiết bị này không mở được ảnh HEIC. Hãy chọn ảnh lưu dạng JPG.',
  },
}

export function composeGapCopy(locale: string): ComposeGapCopy {
  return copy[resolveLegalDocumentLocale(resolveSupportedLocaleTag(locale) || 'en')]
}
