import { resolveLegalDocumentLocale, resolveSupportedLocaleTag, type LegalDocumentLocale } from './config'

type BioCopy = { translate: string; translating: string; original: string; translation: string; failed: string; processing: string; ready: string; partial: string }
const copy: Record<LegalDocumentLocale, BioCopy> = {
  ko: { translate: '번역 보기', translating: '번역 중…', original: '원문 보기', translation: '번역 보기', failed: '번역하지 못했습니다. 다시 눌러 시도해 주세요.', processing: '소개를 저장했습니다. 번역을 준비하고 있습니다.', ready: '소개와 번역이 반영되었습니다.', partial: '소개가 반영되었습니다. 일부 언어는 번역이 준비되지 않았습니다.' },
  en: { translate: 'See translation', translating: 'Translating…', original: 'See original', translation: 'See translation', failed: 'Translation failed. Tap to try again.', processing: 'Bio saved. Preparing translations.', ready: 'Bio and translations are published.', partial: 'Bio published. Some translations are unavailable.' },
  ja: { translate: '翻訳を見る', translating: '翻訳中…', original: '原文を見る', translation: '翻訳を見る', failed: '翻訳できませんでした。タップして再試行してください。', processing: '自己紹介を保存しました。翻訳を準備しています。', ready: '自己紹介と翻訳を公開しました。', partial: '自己紹介を公開しました。一部の翻訳は準備できませんでした。' },
  'zh-CN': { translate: '查看翻译', translating: '翻译中…', original: '查看原文', translation: '查看翻译', failed: '翻译失败，请点击重试。', processing: '个人简介已保存，正在准备翻译。', ready: '个人简介和翻译已发布。', partial: '个人简介已发布，部分翻译暂不可用。' },
  'zh-TW': { translate: '查看翻譯', translating: '翻譯中…', original: '查看原文', translation: '查看翻譯', failed: '翻譯失敗，請點擊重試。', processing: '個人簡介已儲存，正在準備翻譯。', ready: '個人簡介與翻譯已發布。', partial: '個人簡介已發布，部分翻譯暫不可用。' },
  fr: { translate: 'Voir la traduction', translating: 'Traduction…', original: 'Voir l’original', translation: 'Voir la traduction', failed: 'Échec de la traduction. Touchez pour réessayer.', processing: 'Présentation enregistrée. Traductions en préparation.', ready: 'Présentation et traductions publiées.', partial: 'Présentation publiée. Certaines traductions sont indisponibles.' },
  de: { translate: 'Übersetzung ansehen', translating: 'Wird übersetzt…', original: 'Original ansehen', translation: 'Übersetzung ansehen', failed: 'Übersetzung fehlgeschlagen. Zum Wiederholen antippen.', processing: 'Profiltext gespeichert. Übersetzungen werden vorbereitet.', ready: 'Profiltext und Übersetzungen veröffentlicht.', partial: 'Profiltext veröffentlicht. Einige Übersetzungen sind nicht verfügbar.' },
  es: { translate: 'Ver traducción', translating: 'Traduciendo…', original: 'Ver original', translation: 'Ver traducción', failed: 'No se pudo traducir. Toca para reintentar.', processing: 'Biografía guardada. Preparando traducciones.', ready: 'Biografía y traducciones publicadas.', partial: 'Biografía publicada. Algunas traducciones no están disponibles.' },
  pt: { translate: 'Ver tradução', translating: 'Traduzindo…', original: 'Ver original', translation: 'Ver tradução', failed: 'Falha na tradução. Toque para tentar novamente.', processing: 'Biografia salva. Preparando traduções.', ready: 'Biografia e traduções publicadas.', partial: 'Biografia publicada. Algumas traduções estão indisponíveis.' },
  it: { translate: 'Vedi traduzione', translating: 'Traduzione in corso…', original: 'Vedi originale', translation: 'Vedi traduzione', failed: 'Traduzione non riuscita. Tocca per riprovare.', processing: 'Biografia salvata. Traduzioni in preparazione.', ready: 'Biografia e traduzioni pubblicate.', partial: 'Biografia pubblicata. Alcune traduzioni non sono disponibili.' },
  ru: { translate: 'Показать перевод', translating: 'Переводим…', original: 'Показать оригинал', translation: 'Показать перевод', failed: 'Не удалось перевести. Нажмите, чтобы повторить.', processing: 'Описание сохранено. Готовим переводы.', ready: 'Описание и переводы опубликованы.', partial: 'Описание опубликовано. Некоторые переводы недоступны.' },
  ar: { translate: 'عرض الترجمة', translating: 'جارٍ الترجمة…', original: 'عرض الأصل', translation: 'عرض الترجمة', failed: 'تعذرت الترجمة. اضغط للمحاولة مجددًا.', processing: 'تم حفظ النبذة. جارٍ إعداد الترجمات.', ready: 'تم نشر النبذة والترجمات.', partial: 'تم نشر النبذة. بعض الترجمات غير متاحة.' },
  hi: { translate: 'अनुवाद देखें', translating: 'अनुवाद हो रहा है…', original: 'मूल देखें', translation: 'अनुवाद देखें', failed: 'अनुवाद नहीं हो सका। फिर से प्रयास करने के लिए टैप करें।', processing: 'परिचय सहेजा गया। अनुवाद तैयार हो रहे हैं।', ready: 'परिचय और अनुवाद प्रकाशित हो गए हैं।', partial: 'परिचय प्रकाशित हो गया। कुछ अनुवाद उपलब्ध नहीं हैं।' },
  th: { translate: 'ดูคำแปล', translating: 'กำลังแปล…', original: 'ดูต้นฉบับ', translation: 'ดูคำแปล', failed: 'แปลไม่สำเร็จ แตะเพื่อลองอีกครั้ง', processing: 'บันทึกประวัติแล้ว กำลังเตรียมคำแปล', ready: 'เผยแพร่ประวัติและคำแปลแล้ว', partial: 'เผยแพร่ประวัติแล้ว คำแปลบางภาษายังไม่พร้อม' },
  vi: { translate: 'Xem bản dịch', translating: 'Đang dịch…', original: 'Xem bản gốc', translation: 'Xem bản dịch', failed: 'Không thể dịch. Nhấn để thử lại.', processing: 'Đã lưu tiểu sử. Đang chuẩn bị bản dịch.', ready: 'Đã đăng tiểu sử và bản dịch.', partial: 'Đã đăng tiểu sử. Một số bản dịch chưa có.' },
}
export function profileBioCopy(locale: string): BioCopy {
  return copy[resolveLegalDocumentLocale(resolveSupportedLocaleTag(locale) || 'en')]
}
