import {
  DEFAULT_LOCALE,
  resolveLegalDocumentLocale,
  resolveSupportedLocaleTag,
  type LegalDocumentLocale,
} from '@/i18n/config'

export type LanguageOnboardingCopy = {
  menuItemLabel: string
  title: string
  descriptionLabel: string
  speechAppealLabel: string
  searchPlaceholder: string
  noResultsLabel: string
  confirmButtonLabel: string
  laterHintLabel: string
  closeLabel: string
  priorityLanguagesLabel: string
  allLanguagesLabel: string
}

const LANGUAGE_ONBOARDING_COPY_BY_LOCALE = {
  ko: {
    menuItemLabel: '언어',
    title: '보고 싶은 언어를 선택해주세요',
    descriptionLabel: '상대방의 메시지를 번역해서 보여줄 언어예요.',
    speechAppealLabel: '말할 때는 어떤 언어를 써도 괜찮아요. 자동으로 알아듣고 번역해요.',
    searchPlaceholder: '언어 검색',
    noResultsLabel: '검색 결과가 없어요.',
    confirmButtonLabel: '시작하기',
    laterHintLabel: '이 설정은 메뉴에서 언제든 다시 바꿀 수 있어요.',
    closeLabel: '닫기',
    priorityLanguagesLabel: '주요 언어',
    allLanguagesLabel: '전체 언어',
  },
  en: {
    menuItemLabel: 'Language',
    title: 'Choose the language you want to see',
    descriptionLabel: "The other person's messages will be translated into this language.",
    speechAppealLabel: 'Speak in any language you like — Mingle picks it up and translates it automatically.',
    searchPlaceholder: 'Search languages',
    noResultsLabel: 'No matching languages.',
    confirmButtonLabel: 'Get started',
    laterHintLabel: 'You can change this anytime from the menu.',
    closeLabel: 'Close',
    priorityLanguagesLabel: 'Popular languages',
    allLanguagesLabel: 'All languages',
  },
  ja: {
    menuItemLabel: '言語',
    title: '見たい言語を選択してください',
    descriptionLabel: '相手のメッセージを翻訳して表示する言語です。',
    speechAppealLabel: '話すときはどの言語でも大丈夫です。自動で認識して翻訳します。',
    searchPlaceholder: '言語を検索',
    noResultsLabel: '一致する言語がありません。',
    confirmButtonLabel: 'はじめる',
    laterHintLabel: 'この設定はメニューからいつでも変更できます。',
    closeLabel: '閉じる',
    priorityLanguagesLabel: 'よく使われる言語',
    allLanguagesLabel: 'すべての言語',
  },
  'zh-CN': {
    menuItemLabel: '语言',
    title: '请选择您想查看的语言',
    descriptionLabel: '对方的消息将翻译成这种语言显示给您。',
    speechAppealLabel: '说话时用任何语言都可以，会自动识别并翻译。',
    searchPlaceholder: '搜索语言',
    noResultsLabel: '没有找到匹配的语言。',
    confirmButtonLabel: '开始使用',
    laterHintLabel: '此设置可以随时在菜单中更改。',
    closeLabel: '关闭',
    priorityLanguagesLabel: '常用语言',
    allLanguagesLabel: '全部语言',
  },
  'zh-TW': {
    menuItemLabel: '語言',
    title: '請選擇您想查看的語言',
    descriptionLabel: '對方的訊息將翻譯成這個語言顯示給您。',
    speechAppealLabel: '說話時用任何語言都可以，會自動辨識並翻譯。',
    searchPlaceholder: '搜尋語言',
    noResultsLabel: '找不到符合的語言。',
    confirmButtonLabel: '開始使用',
    laterHintLabel: '此設定可以隨時在選單中變更。',
    closeLabel: '關閉',
    priorityLanguagesLabel: '常用語言',
    allLanguagesLabel: '全部語言',
  },
  fr: {
    menuItemLabel: 'Langue',
    title: 'Choisissez la langue que vous voulez voir',
    descriptionLabel: 'Les messages de votre interlocuteur seront traduits dans cette langue.',
    speechAppealLabel: 'Parlez dans la langue de votre choix : elle est reconnue et traduite automatiquement.',
    searchPlaceholder: 'Rechercher une langue',
    noResultsLabel: 'Aucune langue correspondante.',
    confirmButtonLabel: 'Commencer',
    laterHintLabel: 'Vous pouvez modifier ce choix à tout moment depuis le menu.',
    closeLabel: 'Fermer',
    priorityLanguagesLabel: 'Langues populaires',
    allLanguagesLabel: 'Toutes les langues',
  },
  de: {
    menuItemLabel: 'Sprache',
    title: 'Wähle die Sprache, die du sehen möchtest',
    descriptionLabel: 'Die Nachrichten deines Gesprächspartners werden in diese Sprache übersetzt.',
    speechAppealLabel: 'Sprich in jeder Sprache, die du möchtest – sie wird automatisch erkannt und übersetzt.',
    searchPlaceholder: 'Sprache suchen',
    noResultsLabel: 'Keine passende Sprache gefunden.',
    confirmButtonLabel: 'Loslegen',
    laterHintLabel: 'Du kannst dies jederzeit im Menü ändern.',
    closeLabel: 'Schließen',
    priorityLanguagesLabel: 'Beliebte Sprachen',
    allLanguagesLabel: 'Alle Sprachen',
  },
  es: {
    menuItemLabel: 'Idioma',
    title: 'Elige el idioma que quieres ver',
    descriptionLabel: 'Los mensajes de la otra persona se traducirán a este idioma.',
    speechAppealLabel: 'Habla en el idioma que prefieras: se reconoce y traduce automáticamente.',
    searchPlaceholder: 'Buscar idioma',
    noResultsLabel: 'No se encontraron idiomas.',
    confirmButtonLabel: 'Empezar',
    laterHintLabel: 'Puedes cambiarlo en cualquier momento desde el menú.',
    closeLabel: 'Cerrar',
    priorityLanguagesLabel: 'Idiomas populares',
    allLanguagesLabel: 'Todos los idiomas',
  },
  pt: {
    menuItemLabel: 'Idioma',
    title: 'Escolha o idioma que você quer ver',
    descriptionLabel: 'As mensagens da outra pessoa serão traduzidas para este idioma.',
    speechAppealLabel: 'Fale no idioma que preferir — é reconhecido e traduzido automaticamente.',
    searchPlaceholder: 'Buscar idioma',
    noResultsLabel: 'Nenhum idioma encontrado.',
    confirmButtonLabel: 'Começar',
    laterHintLabel: 'Você pode alterar isso a qualquer momento pelo menu.',
    closeLabel: 'Fechar',
    priorityLanguagesLabel: 'Idiomas populares',
    allLanguagesLabel: 'Todos os idiomas',
  },
  it: {
    menuItemLabel: 'Lingua',
    title: 'Scegli la lingua che vuoi vedere',
    descriptionLabel: 'I messaggi dell’altra persona verranno tradotti in questa lingua.',
    speechAppealLabel: 'Parla nella lingua che preferisci: viene riconosciuta e tradotta automaticamente.',
    searchPlaceholder: 'Cerca lingua',
    noResultsLabel: 'Nessuna lingua trovata.',
    confirmButtonLabel: 'Inizia',
    laterHintLabel: 'Puoi modificarlo in qualsiasi momento dal menu.',
    closeLabel: 'Chiudi',
    priorityLanguagesLabel: 'Lingue popolari',
    allLanguagesLabel: 'Tutte le lingue',
  },
  ru: {
    menuItemLabel: 'Язык',
    title: 'Выберите язык, который хотите видеть',
    descriptionLabel: 'Сообщения собеседника будут переведены на этот язык.',
    speechAppealLabel: 'Говорите на любом удобном языке — он распознаётся и переводится автоматически.',
    searchPlaceholder: 'Поиск языка',
    noResultsLabel: 'Совпадений не найдено.',
    confirmButtonLabel: 'Начать',
    laterHintLabel: 'Вы можете изменить это в любое время в меню.',
    closeLabel: 'Закрыть',
    priorityLanguagesLabel: 'Популярные языки',
    allLanguagesLabel: 'Все языки',
  },
  ar: {
    menuItemLabel: 'اللغة',
    title: 'اختر اللغة التي تريد رؤيتها',
    descriptionLabel: 'سيتم ترجمة رسائل الطرف الآخر إلى هذه اللغة.',
    speechAppealLabel: 'تحدث بأي لغة تريدها، سيتم التعرف عليها وترجمتها تلقائيًا.',
    searchPlaceholder: 'ابحث عن لغة',
    noResultsLabel: 'لا توجد لغات مطابقة.',
    confirmButtonLabel: 'ابدأ',
    laterHintLabel: 'يمكنك تغيير هذا في أي وقت من القائمة.',
    closeLabel: 'إغلاق',
    priorityLanguagesLabel: 'اللغات الشائعة',
    allLanguagesLabel: 'جميع اللغات',
  },
  hi: {
    menuItemLabel: 'भाषा',
    title: 'आप जो भाषा देखना चाहते हैं उसे चुनें',
    descriptionLabel: 'सामने वाले के संदेश इसी भाषा में अनुवाद करके दिखाए जाएंगे।',
    speechAppealLabel: 'आप किसी भी भाषा में बोल सकते हैं, इसे अपने आप पहचानकर अनुवाद कर दिया जाएगा।',
    searchPlaceholder: 'भाषा खोजें',
    noResultsLabel: 'कोई मिलती-जुलती भाषा नहीं मिली।',
    confirmButtonLabel: 'शुरू करें',
    laterHintLabel: 'आप इसे कभी भी मेनू से बदल सकते हैं।',
    closeLabel: 'बंद करें',
    priorityLanguagesLabel: 'लोकप्रिय भाषाएं',
    allLanguagesLabel: 'सभी भाषाएं',
  },
  th: {
    menuItemLabel: 'ภาษา',
    title: 'เลือกภาษาที่คุณต้องการดู',
    descriptionLabel: 'ข้อความของอีกฝ่ายจะถูกแปลเป็นภาษานี้ให้คุณดู',
    speechAppealLabel: 'พูดภาษาอะไรก็ได้ตามที่คุณสะดวก ระบบจะจดจำและแปลให้โดยอัตโนมัติ',
    searchPlaceholder: 'ค้นหาภาษา',
    noResultsLabel: 'ไม่พบภาษาที่ตรงกัน',
    confirmButtonLabel: 'เริ่มเลย',
    laterHintLabel: 'คุณสามารถเปลี่ยนได้ทุกเมื่อจากเมนู',
    closeLabel: 'ปิด',
    priorityLanguagesLabel: 'ภาษายอดนิยม',
    allLanguagesLabel: 'ภาษาทั้งหมด',
  },
  vi: {
    menuItemLabel: 'Ngôn ngữ',
    title: 'Chọn ngôn ngữ bạn muốn xem',
    descriptionLabel: 'Tin nhắn của người kia sẽ được dịch sang ngôn ngữ này.',
    speechAppealLabel: 'Bạn có thể nói bất kỳ ngôn ngữ nào mình muốn, hệ thống sẽ tự động nhận diện và dịch.',
    searchPlaceholder: 'Tìm ngôn ngữ',
    noResultsLabel: 'Không tìm thấy ngôn ngữ phù hợp.',
    confirmButtonLabel: 'Bắt đầu',
    laterHintLabel: 'Bạn có thể thay đổi bất cứ lúc nào từ menu.',
    closeLabel: 'Đóng',
    priorityLanguagesLabel: 'Ngôn ngữ phổ biến',
    allLanguagesLabel: 'Tất cả ngôn ngữ',
  },
} satisfies Record<LegalDocumentLocale, LanguageOnboardingCopy>

export function resolveLanguageOnboardingCopy(uiLocale: string): LanguageOnboardingCopy {
  const supportedLocale = resolveSupportedLocaleTag(uiLocale) ?? DEFAULT_LOCALE
  const resolvedLocale = resolveLegalDocumentLocale(supportedLocale)

  return LANGUAGE_ONBOARDING_COPY_BY_LOCALE[resolvedLocale] ?? LANGUAGE_ONBOARDING_COPY_BY_LOCALE.en
}
