import {
  DEFAULT_LOCALE,
  resolveLegalDocumentLocale,
  resolveSupportedLocaleTag,
  type LegalDocumentLocale,
} from '@/i18n/config'

export type LanguageOnboardingCopy = {
  menuItemLabel: string
  title: string
  sourceSectionLabel: string
  sourceDescriptionLabel: string
  targetSectionLabel: string
  targetDescriptionLabel: string
  searchPlaceholder: string
  noResultsLabel: string
  confirmButtonLabel: string
  laterHintLabel: string
  closeLabel: string
  maxTargetLanguagesReachedLabel: string
}

const LANGUAGE_ONBOARDING_COPY_BY_LOCALE = {
  ko: {
    menuItemLabel: '언어',
    title: '언어를 선택해 주세요',
    sourceSectionLabel: '내 언어',
    sourceDescriptionLabel: '내가 말하거나 입력할 때 사용하는 언어예요.',
    targetSectionLabel: '번역 언어',
    targetDescriptionLabel: '상대방의 말을 번역해서 보여줄 언어예요. 여러 개 선택할 수 있어요.',
    searchPlaceholder: '언어 검색',
    noResultsLabel: '검색 결과가 없어요.',
    confirmButtonLabel: '시작하기',
    laterHintLabel: '이 설정은 메뉴에서 언제든 다시 바꿀 수 있어요.',
    closeLabel: '닫기',
    maxTargetLanguagesReachedLabel: '최대 5개까지 선택할 수 있어요.',
  },
  en: {
    menuItemLabel: 'Language',
    title: 'Choose your language',
    sourceSectionLabel: 'My language',
    sourceDescriptionLabel: 'The language you speak or type in.',
    targetSectionLabel: 'Translate into',
    targetDescriptionLabel: "The language the other person's messages will be translated into. You can pick more than one.",
    searchPlaceholder: 'Search languages',
    noResultsLabel: 'No matching languages.',
    confirmButtonLabel: 'Get started',
    laterHintLabel: 'You can change this anytime from the menu.',
    closeLabel: 'Close',
    maxTargetLanguagesReachedLabel: 'You can select up to 5 languages.',
  },
  ja: {
    menuItemLabel: '言語',
    title: '言語を選択してください',
    sourceSectionLabel: '自分の言語',
    sourceDescriptionLabel: '自分が話したり入力したりするときに使う言語です。',
    targetSectionLabel: '翻訳先の言語',
    targetDescriptionLabel: '相手の発言を翻訳して表示する言語です。複数選択できます。',
    searchPlaceholder: '言語を検索',
    noResultsLabel: '一致する言語がありません。',
    confirmButtonLabel: 'はじめる',
    laterHintLabel: 'この設定はメニューからいつでも変更できます。',
    closeLabel: '閉じる',
    maxTargetLanguagesReachedLabel: '最大5つまで選択できます。',
  },
  'zh-CN': {
    menuItemLabel: '语言',
    title: '请选择语言',
    sourceSectionLabel: '我的语言',
    sourceDescriptionLabel: '您说话或输入时使用的语言。',
    targetSectionLabel: '翻译成的语言',
    targetDescriptionLabel: '将对方的话翻译显示成的语言，可以多选。',
    searchPlaceholder: '搜索语言',
    noResultsLabel: '没有找到匹配的语言。',
    confirmButtonLabel: '开始使用',
    laterHintLabel: '此设置可以随时在菜单中更改。',
    closeLabel: '关闭',
    maxTargetLanguagesReachedLabel: '最多可以选择5种语言。',
  },
  'zh-TW': {
    menuItemLabel: '語言',
    title: '請選擇語言',
    sourceSectionLabel: '我的語言',
    sourceDescriptionLabel: '您說話或輸入時使用的語言。',
    targetSectionLabel: '翻譯成的語言',
    targetDescriptionLabel: '將對方的話翻譯顯示成的語言，可以多選。',
    searchPlaceholder: '搜尋語言',
    noResultsLabel: '找不到符合的語言。',
    confirmButtonLabel: '開始使用',
    laterHintLabel: '此設定可以隨時在選單中變更。',
    closeLabel: '關閉',
    maxTargetLanguagesReachedLabel: '最多可以選擇5種語言。',
  },
  fr: {
    menuItemLabel: 'Langue',
    title: 'Choisissez votre langue',
    sourceSectionLabel: 'Ma langue',
    sourceDescriptionLabel: 'La langue que vous parlez ou utilisez pour écrire.',
    targetSectionLabel: 'Traduire vers',
    targetDescriptionLabel: 'La ou les langues dans lesquelles traduire les messages de votre interlocuteur. Vous pouvez en choisir plusieurs.',
    searchPlaceholder: 'Rechercher une langue',
    noResultsLabel: 'Aucune langue correspondante.',
    confirmButtonLabel: 'Commencer',
    laterHintLabel: 'Vous pouvez modifier ce choix à tout moment depuis le menu.',
    closeLabel: 'Fermer',
    maxTargetLanguagesReachedLabel: 'Vous pouvez sélectionner jusqu’à 5 langues.',
  },
  de: {
    menuItemLabel: 'Sprache',
    title: 'Wähle deine Sprache',
    sourceSectionLabel: 'Meine Sprache',
    sourceDescriptionLabel: 'Die Sprache, die du sprichst oder zum Tippen verwendest.',
    targetSectionLabel: 'Übersetzen in',
    targetDescriptionLabel: 'Die Sprache(n), in die die Nachrichten deines Gesprächspartners übersetzt werden. Mehrfachauswahl möglich.',
    searchPlaceholder: 'Sprache suchen',
    noResultsLabel: 'Keine passende Sprache gefunden.',
    confirmButtonLabel: 'Loslegen',
    laterHintLabel: 'Du kannst dies jederzeit im Menü ändern.',
    closeLabel: 'Schließen',
    maxTargetLanguagesReachedLabel: 'Du kannst bis zu 5 Sprachen auswählen.',
  },
  es: {
    menuItemLabel: 'Idioma',
    title: 'Elige tu idioma',
    sourceSectionLabel: 'Mi idioma',
    sourceDescriptionLabel: 'El idioma que hablas o usas para escribir.',
    targetSectionLabel: 'Traducir a',
    targetDescriptionLabel: 'El idioma o idiomas a los que se traducirán los mensajes de la otra persona. Puedes elegir varios.',
    searchPlaceholder: 'Buscar idioma',
    noResultsLabel: 'No se encontraron idiomas.',
    confirmButtonLabel: 'Empezar',
    laterHintLabel: 'Puedes cambiarlo en cualquier momento desde el menú.',
    closeLabel: 'Cerrar',
    maxTargetLanguagesReachedLabel: 'Puedes seleccionar hasta 5 idiomas.',
  },
  pt: {
    menuItemLabel: 'Idioma',
    title: 'Escolha seu idioma',
    sourceSectionLabel: 'Meu idioma',
    sourceDescriptionLabel: 'O idioma que você fala ou usa para digitar.',
    targetSectionLabel: 'Traduzir para',
    targetDescriptionLabel: 'O(s) idioma(s) para o qual as mensagens da outra pessoa serão traduzidas. Você pode escolher mais de um.',
    searchPlaceholder: 'Buscar idioma',
    noResultsLabel: 'Nenhum idioma encontrado.',
    confirmButtonLabel: 'Começar',
    laterHintLabel: 'Você pode alterar isso a qualquer momento pelo menu.',
    closeLabel: 'Fechar',
    maxTargetLanguagesReachedLabel: 'Você pode selecionar até 5 idiomas.',
  },
  it: {
    menuItemLabel: 'Lingua',
    title: 'Scegli la tua lingua',
    sourceSectionLabel: 'La mia lingua',
    sourceDescriptionLabel: 'La lingua che parli o usi per scrivere.',
    targetSectionLabel: 'Traduci in',
    targetDescriptionLabel: 'La lingua o le lingue in cui tradurre i messaggi dell’altra persona. Puoi sceglierne più di una.',
    searchPlaceholder: 'Cerca lingua',
    noResultsLabel: 'Nessuna lingua trovata.',
    confirmButtonLabel: 'Inizia',
    laterHintLabel: 'Puoi modificarlo in qualsiasi momento dal menu.',
    closeLabel: 'Chiudi',
    maxTargetLanguagesReachedLabel: 'Puoi selezionare fino a 5 lingue.',
  },
  ru: {
    menuItemLabel: 'Язык',
    title: 'Выберите язык',
    sourceSectionLabel: 'Мой язык',
    sourceDescriptionLabel: 'Язык, на котором вы говорите или печатаете.',
    targetSectionLabel: 'Переводить на',
    targetDescriptionLabel: 'Язык(и), на который будут переводиться сообщения собеседника. Можно выбрать несколько.',
    searchPlaceholder: 'Поиск языка',
    noResultsLabel: 'Совпадений не найдено.',
    confirmButtonLabel: 'Начать',
    laterHintLabel: 'Вы можете изменить это в любое время в меню.',
    closeLabel: 'Закрыть',
    maxTargetLanguagesReachedLabel: 'Можно выбрать до 5 языков.',
  },
  ar: {
    menuItemLabel: 'اللغة',
    title: 'اختر لغتك',
    sourceSectionLabel: 'لغتي',
    sourceDescriptionLabel: 'اللغة التي تتحدث بها أو تكتب بها.',
    targetSectionLabel: 'الترجمة إلى',
    targetDescriptionLabel: 'اللغة أو اللغات التي سيتم ترجمة رسائل الطرف الآخر إليها. يمكنك اختيار أكثر من لغة.',
    searchPlaceholder: 'ابحث عن لغة',
    noResultsLabel: 'لا توجد لغات مطابقة.',
    confirmButtonLabel: 'ابدأ',
    laterHintLabel: 'يمكنك تغيير هذا في أي وقت من القائمة.',
    closeLabel: 'إغلاق',
    maxTargetLanguagesReachedLabel: 'يمكنك اختيار حتى 5 لغات.',
  },
  hi: {
    menuItemLabel: 'भाषा',
    title: 'अपनी भाषा चुनें',
    sourceSectionLabel: 'मेरी भाषा',
    sourceDescriptionLabel: 'वह भाषा जिसमें आप बोलते या टाइप करते हैं।',
    targetSectionLabel: 'अनुवाद भाषा',
    targetDescriptionLabel: 'वह भाषा (या भाषाएं) जिनमें सामने वाले के संदेशों का अनुवाद दिखाया जाएगा। आप एक से अधिक चुन सकते हैं।',
    searchPlaceholder: 'भाषा खोजें',
    noResultsLabel: 'कोई मिलती-जुलती भाषा नहीं मिली।',
    confirmButtonLabel: 'शुरू करें',
    laterHintLabel: 'आप इसे कभी भी मेनू से बदल सकते हैं।',
    closeLabel: 'बंद करें',
    maxTargetLanguagesReachedLabel: 'आप अधिकतम 5 भाषाएं चुन सकते हैं।',
  },
  th: {
    menuItemLabel: 'ภาษา',
    title: 'เลือกภาษาของคุณ',
    sourceSectionLabel: 'ภาษาของฉัน',
    sourceDescriptionLabel: 'ภาษาที่คุณพูดหรือใช้พิมพ์',
    targetSectionLabel: 'แปลเป็นภาษา',
    targetDescriptionLabel: 'ภาษาที่จะใช้แปลข้อความของอีกฝ่าย เลือกได้มากกว่า 1 ภาษา',
    searchPlaceholder: 'ค้นหาภาษา',
    noResultsLabel: 'ไม่พบภาษาที่ตรงกัน',
    confirmButtonLabel: 'เริ่มเลย',
    laterHintLabel: 'คุณสามารถเปลี่ยนได้ทุกเมื่อจากเมนู',
    closeLabel: 'ปิด',
    maxTargetLanguagesReachedLabel: 'เลือกได้สูงสุด 5 ภาษา',
  },
  vi: {
    menuItemLabel: 'Ngôn ngữ',
    title: 'Chọn ngôn ngữ của bạn',
    sourceSectionLabel: 'Ngôn ngữ của tôi',
    sourceDescriptionLabel: 'Ngôn ngữ bạn nói hoặc dùng để nhập.',
    targetSectionLabel: 'Dịch sang',
    targetDescriptionLabel: 'Ngôn ngữ để dịch tin nhắn của người kia sang. Bạn có thể chọn nhiều ngôn ngữ.',
    searchPlaceholder: 'Tìm ngôn ngữ',
    noResultsLabel: 'Không tìm thấy ngôn ngữ phù hợp.',
    confirmButtonLabel: 'Bắt đầu',
    laterHintLabel: 'Bạn có thể thay đổi bất cứ lúc nào từ menu.',
    closeLabel: 'Đóng',
    maxTargetLanguagesReachedLabel: 'Bạn có thể chọn tối đa 5 ngôn ngữ.',
  },
} satisfies Record<LegalDocumentLocale, LanguageOnboardingCopy>

export function resolveLanguageOnboardingCopy(uiLocale: string): LanguageOnboardingCopy {
  const supportedLocale = resolveSupportedLocaleTag(uiLocale) ?? DEFAULT_LOCALE
  const resolvedLocale = resolveLegalDocumentLocale(supportedLocale)

  return LANGUAGE_ONBOARDING_COPY_BY_LOCALE[resolvedLocale] ?? LANGUAGE_ONBOARDING_COPY_BY_LOCALE.en
}
