import {
  DEFAULT_LOCALE,
  resolveLegalDocumentLocale,
  resolveSupportedLocaleTag,
  type LegalDocumentLocale,
} from '@/i18n/config'

export type LanguageOnboardingCopy = {
  menuItemLabel: string
  title: string
  descriptionLabel: string
  searchPlaceholder: string
  noResultsLabel: string
  confirmButtonLabel: string
  laterHintLabel: string
  closeLabel: string
  priorityLanguagesLabel: string
  allLanguagesLabel: string
}

const LANGUAGE_ONBOARDING_COPY_BY_LOCALE = {
  ko: {
    menuItemLabel: '언어',
    title: '가장 편한 언어를 선택해주세요',
    descriptionLabel: '선택된 언어는 앱의 기본 언어로 쓰여요.',
    searchPlaceholder: '언어 검색',
    noResultsLabel: '검색 결과가 없어요.',
    confirmButtonLabel: '시작하기',
    laterHintLabel: '이 설정은 메뉴에서 언제든 다시 바꿀 수 있어요.',
    closeLabel: '닫기',
    priorityLanguagesLabel: '주요 언어',
    allLanguagesLabel: '전체 언어',
  },
  en: {
    menuItemLabel: 'Language',
    title: 'Choose your most comfortable language',
    descriptionLabel: "This becomes your app's default language.",
    searchPlaceholder: 'Search languages',
    noResultsLabel: 'No matching languages.',
    confirmButtonLabel: 'Get started',
    laterHintLabel: 'You can change this anytime from the menu.',
    closeLabel: 'Close',
    priorityLanguagesLabel: 'Popular languages',
    allLanguagesLabel: 'All languages',
  },
  ja: {
    menuItemLabel: '言語',
    title: '一番使いやすい言語を選択してください',
    descriptionLabel: '選択した言語がアプリの基本言語になります。',
    searchPlaceholder: '言語を検索',
    noResultsLabel: '一致する言語がありません。',
    confirmButtonLabel: 'はじめる',
    laterHintLabel: 'この設定はメニューからいつでも変更できます。',
    closeLabel: '閉じる',
    priorityLanguagesLabel: 'よく使われる言語',
    allLanguagesLabel: 'すべての言語',
  },
  'zh-CN': {
    menuItemLabel: '语言',
    title: '请选择您最习惯的语言',
    descriptionLabel: '选择的语言将成为应用的默认语言。',
    searchPlaceholder: '搜索语言',
    noResultsLabel: '没有找到匹配的语言。',
    confirmButtonLabel: '开始使用',
    laterHintLabel: '此设置可以随时在菜单中更改。',
    closeLabel: '关闭',
    priorityLanguagesLabel: '常用语言',
    allLanguagesLabel: '全部语言',
  },
  'zh-TW': {
    menuItemLabel: '語言',
    title: '請選擇您最習慣的語言',
    descriptionLabel: '選擇的語言會成為應用程式的預設語言。',
    searchPlaceholder: '搜尋語言',
    noResultsLabel: '找不到符合的語言。',
    confirmButtonLabel: '開始使用',
    laterHintLabel: '此設定可以隨時在選單中變更。',
    closeLabel: '關閉',
    priorityLanguagesLabel: '常用語言',
    allLanguagesLabel: '全部語言',
  },
  fr: {
    menuItemLabel: 'Langue',
    title: 'Choisissez la langue avec laquelle vous êtes le plus à l’aise',
    descriptionLabel: 'La langue choisie devient la langue par défaut de l’appli.',
    searchPlaceholder: 'Rechercher une langue',
    noResultsLabel: 'Aucune langue correspondante.',
    confirmButtonLabel: 'Commencer',
    laterHintLabel: 'Vous pouvez modifier ce choix à tout moment depuis le menu.',
    closeLabel: 'Fermer',
    priorityLanguagesLabel: 'Langues populaires',
    allLanguagesLabel: 'Toutes les langues',
  },
  de: {
    menuItemLabel: 'Sprache',
    title: 'Wähle die Sprache, die dir am angenehmsten ist',
    descriptionLabel: 'Die gewählte Sprache wird die Standardsprache der App.',
    searchPlaceholder: 'Sprache suchen',
    noResultsLabel: 'Keine passende Sprache gefunden.',
    confirmButtonLabel: 'Loslegen',
    laterHintLabel: 'Du kannst dies jederzeit im Menü ändern.',
    closeLabel: 'Schließen',
    priorityLanguagesLabel: 'Beliebte Sprachen',
    allLanguagesLabel: 'Alle Sprachen',
  },
  es: {
    menuItemLabel: 'Idioma',
    title: 'Elige el idioma con el que te sientas más cómodo',
    descriptionLabel: 'El idioma elegido será el idioma predeterminado de la app.',
    searchPlaceholder: 'Buscar idioma',
    noResultsLabel: 'No se encontraron idiomas.',
    confirmButtonLabel: 'Empezar',
    laterHintLabel: 'Puedes cambiarlo en cualquier momento desde el menú.',
    closeLabel: 'Cerrar',
    priorityLanguagesLabel: 'Idiomas populares',
    allLanguagesLabel: 'Todos los idiomas',
  },
  pt: {
    menuItemLabel: 'Idioma',
    title: 'Escolha o idioma com o qual você se sente mais confortável',
    descriptionLabel: 'O idioma escolhido se torna o idioma padrão do app.',
    searchPlaceholder: 'Buscar idioma',
    noResultsLabel: 'Nenhum idioma encontrado.',
    confirmButtonLabel: 'Começar',
    laterHintLabel: 'Você pode alterar isso a qualquer momento pelo menu.',
    closeLabel: 'Fechar',
    priorityLanguagesLabel: 'Idiomas populares',
    allLanguagesLabel: 'Todos os idiomas',
  },
  it: {
    menuItemLabel: 'Lingua',
    title: 'Scegli la lingua con cui ti senti più a tuo agio',
    descriptionLabel: 'La lingua scelta diventa la lingua predefinita dell’app.',
    searchPlaceholder: 'Cerca lingua',
    noResultsLabel: 'Nessuna lingua trovata.',
    confirmButtonLabel: 'Inizia',
    laterHintLabel: 'Puoi modificarlo in qualsiasi momento dal menu.',
    closeLabel: 'Chiudi',
    priorityLanguagesLabel: 'Lingue popolari',
    allLanguagesLabel: 'Tutte le lingue',
  },
  ru: {
    menuItemLabel: 'Язык',
    title: 'Выберите язык, который вам удобнее всего',
    descriptionLabel: 'Выбранный язык станет языком приложения по умолчанию.',
    searchPlaceholder: 'Поиск языка',
    noResultsLabel: 'Совпадений не найдено.',
    confirmButtonLabel: 'Начать',
    laterHintLabel: 'Вы можете изменить это в любое время в меню.',
    closeLabel: 'Закрыть',
    priorityLanguagesLabel: 'Популярные языки',
    allLanguagesLabel: 'Все языки',
  },
  ar: {
    menuItemLabel: 'اللغة',
    title: 'اختر اللغة الأكثر راحة بالنسبة لك',
    descriptionLabel: 'ستصبح اللغة المختارة هي اللغة الافتراضية للتطبيق.',
    searchPlaceholder: 'ابحث عن لغة',
    noResultsLabel: 'لا توجد لغات مطابقة.',
    confirmButtonLabel: 'ابدأ',
    laterHintLabel: 'يمكنك تغيير هذا في أي وقت من القائمة.',
    closeLabel: 'إغلاق',
    priorityLanguagesLabel: 'اللغات الشائعة',
    allLanguagesLabel: 'جميع اللغات',
  },
  hi: {
    menuItemLabel: 'भाषा',
    title: 'अपनी सबसे सहज भाषा चुनें',
    descriptionLabel: 'चुनी गई भाषा ऐप की डिफ़ॉल्ट भाषा बन जाएगी।',
    searchPlaceholder: 'भाषा खोजें',
    noResultsLabel: 'कोई मिलती-जुलती भाषा नहीं मिली।',
    confirmButtonLabel: 'शुरू करें',
    laterHintLabel: 'आप इसे कभी भी मेनू से बदल सकते हैं।',
    closeLabel: 'बंद करें',
    priorityLanguagesLabel: 'लोकप्रिय भाषाएं',
    allLanguagesLabel: 'सभी भाषाएं',
  },
  th: {
    menuItemLabel: 'ภาษา',
    title: 'เลือกภาษาที่คุณถนัดที่สุด',
    descriptionLabel: 'ภาษาที่เลือกจะกลายเป็นภาษาเริ่มต้นของแอป',
    searchPlaceholder: 'ค้นหาภาษา',
    noResultsLabel: 'ไม่พบภาษาที่ตรงกัน',
    confirmButtonLabel: 'เริ่มเลย',
    laterHintLabel: 'คุณสามารถเปลี่ยนได้ทุกเมื่อจากเมนู',
    closeLabel: 'ปิด',
    priorityLanguagesLabel: 'ภาษายอดนิยม',
    allLanguagesLabel: 'ภาษาทั้งหมด',
  },
  vi: {
    menuItemLabel: 'Ngôn ngữ',
    title: 'Chọn ngôn ngữ bạn thấy thoải mái nhất',
    descriptionLabel: 'Ngôn ngữ đã chọn sẽ trở thành ngôn ngữ mặc định của ứng dụng.',
    searchPlaceholder: 'Tìm ngôn ngữ',
    noResultsLabel: 'Không tìm thấy ngôn ngữ phù hợp.',
    confirmButtonLabel: 'Bắt đầu',
    laterHintLabel: 'Bạn có thể thay đổi bất cứ lúc nào từ menu.',
    closeLabel: 'Đóng',
    priorityLanguagesLabel: 'Ngôn ngữ phổ biến',
    allLanguagesLabel: 'Tất cả ngôn ngữ',
  },
} satisfies Record<LegalDocumentLocale, LanguageOnboardingCopy>

export function resolveLanguageOnboardingCopy(uiLocale: string): LanguageOnboardingCopy {
  const supportedLocale = resolveSupportedLocaleTag(uiLocale) ?? DEFAULT_LOCALE
  const resolvedLocale = resolveLegalDocumentLocale(supportedLocale)

  return LANGUAGE_ONBOARDING_COPY_BY_LOCALE[resolvedLocale] ?? LANGUAGE_ONBOARDING_COPY_BY_LOCALE.en
}
