import {
  DEFAULT_LOCALE,
  resolveLegalDocumentLocale,
  resolveSupportedLocaleTag,
  type LegalDocumentLocale,
} from '@/i18n/config'

export type LivePhoneDemoRoomManagementCopy = {
  menuItemLabel: string
  pageTitle: string
  backButtonLabel: string
  renameButtonLabel: string
  renameDialogTitle: string
  renameFieldLabel: string
  renameFieldPlaceholder: string
  renameCancelLabel: string
  renameConfirmLabel: string
  renamingLabel: string
  renameEmptyMessage: string
  renameSuccessToastLabel: string
  renameErrorToastLabel: string
}

const ROOM_MANAGEMENT_COPY_BY_LOCALE = {
  ko: {
    menuItemLabel: '대화방 관리',
    pageTitle: '대화방 관리',
    backButtonLabel: '뒤로가기',
    renameButtonLabel: '대화방 이름 변경',
    renameDialogTitle: '대화방 이름 변경',
    renameFieldLabel: '대화방 이름',
    renameFieldPlaceholder: '대화방 이름을 입력해 주세요.',
    renameCancelLabel: '취소',
    renameConfirmLabel: '저장',
    renamingLabel: '저장 중...',
    renameEmptyMessage: '대화방 이름을 입력해 주세요.',
    renameSuccessToastLabel: '대화방 이름이 변경되었습니다.',
    renameErrorToastLabel: '대화방 이름 변경에 실패했습니다. 잠시 후 다시 시도해 주세요.',
  },
  en: {
    menuItemLabel: 'Conversation management',
    pageTitle: 'Conversation management',
    backButtonLabel: 'Go back',
    renameButtonLabel: 'Rename',
    renameDialogTitle: 'Rename conversation',
    renameFieldLabel: 'Conversation name',
    renameFieldPlaceholder: 'Enter a conversation name.',
    renameCancelLabel: 'Cancel',
    renameConfirmLabel: 'Save',
    renamingLabel: 'Saving...',
    renameEmptyMessage: 'Please enter a conversation name.',
    renameSuccessToastLabel: 'The conversation name was updated.',
    renameErrorToastLabel: 'Failed to update the conversation name. Please try again.',
  },
  ja: {
    menuItemLabel: '会話ルーム管理',
    pageTitle: '会話ルーム管理',
    backButtonLabel: '戻る',
    renameButtonLabel: '会話名を変更',
    renameDialogTitle: '会話名を変更',
    renameFieldLabel: '会話名',
    renameFieldPlaceholder: '会話名を入力してください。',
    renameCancelLabel: 'キャンセル',
    renameConfirmLabel: '保存',
    renamingLabel: '保存中...',
    renameEmptyMessage: '会話名を入力してください。',
    renameSuccessToastLabel: '会話名を変更しました。',
    renameErrorToastLabel: '会話名を変更できませんでした。しばらくしてからもう一度お試しください。',
  },
  'zh-CN': {
    menuItemLabel: '会话房间管理',
    pageTitle: '会话房间管理',
    backButtonLabel: '返回',
    renameButtonLabel: '修改会话名称',
    renameDialogTitle: '修改会话名称',
    renameFieldLabel: '会话名称',
    renameFieldPlaceholder: '请输入会话名称。',
    renameCancelLabel: '取消',
    renameConfirmLabel: '保存',
    renamingLabel: '保存中...',
    renameEmptyMessage: '请输入会话名称。',
    renameSuccessToastLabel: '会话名称已更新。',
    renameErrorToastLabel: '更新会话名称失败。请稍后再试。',
  },
  'zh-TW': {
    menuItemLabel: '對話房間管理',
    pageTitle: '對話房間管理',
    backButtonLabel: '返回',
    renameButtonLabel: '變更對話名稱',
    renameDialogTitle: '變更對話名稱',
    renameFieldLabel: '對話名稱',
    renameFieldPlaceholder: '請輸入對話名稱。',
    renameCancelLabel: '取消',
    renameConfirmLabel: '儲存',
    renamingLabel: '儲存中...',
    renameEmptyMessage: '請輸入對話名稱。',
    renameSuccessToastLabel: '對話名稱已更新。',
    renameErrorToastLabel: '更新對話名稱失敗。請稍後再試。',
  },
  fr: {
    menuItemLabel: 'Gestion de la conversation',
    pageTitle: 'Gestion de la conversation',
    backButtonLabel: 'Retour',
    renameButtonLabel: 'Renommer',
    renameDialogTitle: 'Renommer la conversation',
    renameFieldLabel: 'Nom de la conversation',
    renameFieldPlaceholder: 'Saisissez un nom de conversation.',
    renameCancelLabel: 'Annuler',
    renameConfirmLabel: 'Enregistrer',
    renamingLabel: 'Enregistrement...',
    renameEmptyMessage: 'Veuillez saisir un nom de conversation.',
    renameSuccessToastLabel: 'Le nom de la conversation a ete mis a jour.',
    renameErrorToastLabel: "Impossible de modifier le nom de la conversation. Veuillez reessayer.",
  },
  de: {
    menuItemLabel: 'Verwaltung des Gesprächs',
    pageTitle: 'Verwaltung des Gesprächs',
    backButtonLabel: 'Zurück',
    renameButtonLabel: 'Umbenennen',
    renameDialogTitle: 'Gesprach umbenennen',
    renameFieldLabel: 'Gesprachsname',
    renameFieldPlaceholder: 'Geben Sie einen Gesprachsnamen ein.',
    renameCancelLabel: 'Abbrechen',
    renameConfirmLabel: 'Speichern',
    renamingLabel: 'Wird gespeichert...',
    renameEmptyMessage: 'Bitte geben Sie einen Gesprachsnamen ein.',
    renameSuccessToastLabel: 'Der Gesprachsname wurde aktualisiert.',
    renameErrorToastLabel: 'Der Gesprachsname konnte nicht aktualisiert werden. Bitte versuchen Sie es erneut.',
  },
  es: {
    menuItemLabel: 'Gestion de la conversacion',
    pageTitle: 'Gestion de la conversacion',
    backButtonLabel: 'Volver',
    renameButtonLabel: 'Renombrar',
    renameDialogTitle: 'Cambiar nombre de la conversacion',
    renameFieldLabel: 'Nombre de la conversacion',
    renameFieldPlaceholder: 'Introduce un nombre para la conversacion.',
    renameCancelLabel: 'Cancelar',
    renameConfirmLabel: 'Guardar',
    renamingLabel: 'Guardando...',
    renameEmptyMessage: 'Introduce un nombre para la conversacion.',
    renameSuccessToastLabel: 'Se actualizo el nombre de la conversacion.',
    renameErrorToastLabel: 'No se pudo actualizar el nombre de la conversacion. Intentalo de nuevo.',
  },
  pt: {
    menuItemLabel: 'Gerenciamento da conversa',
    pageTitle: 'Gerenciamento da conversa',
    backButtonLabel: 'Voltar',
    renameButtonLabel: 'Renomear',
    renameDialogTitle: 'Renomear conversa',
    renameFieldLabel: 'Nome da conversa',
    renameFieldPlaceholder: 'Digite um nome para a conversa.',
    renameCancelLabel: 'Cancelar',
    renameConfirmLabel: 'Salvar',
    renamingLabel: 'Salvando...',
    renameEmptyMessage: 'Digite um nome para a conversa.',
    renameSuccessToastLabel: 'O nome da conversa foi atualizado.',
    renameErrorToastLabel: 'Nao foi possivel atualizar o nome da conversa. Tente novamente.',
  },
  it: {
    menuItemLabel: 'Gestione della conversazione',
    pageTitle: 'Gestione della conversazione',
    backButtonLabel: 'Indietro',
    renameButtonLabel: 'Rinomina',
    renameDialogTitle: 'Rinomina conversazione',
    renameFieldLabel: 'Nome della conversazione',
    renameFieldPlaceholder: 'Inserisci un nome per la conversazione.',
    renameCancelLabel: 'Annulla',
    renameConfirmLabel: 'Salva',
    renamingLabel: 'Salvataggio...',
    renameEmptyMessage: 'Inserisci un nome per la conversazione.',
    renameSuccessToastLabel: 'Il nome della conversazione e stato aggiornato.',
    renameErrorToastLabel: 'Impossibile aggiornare il nome della conversazione. Riprova.',
  },
  ru: {
    menuItemLabel: 'Управление разговором',
    pageTitle: 'Управление разговором',
    backButtonLabel: 'Назад',
    renameButtonLabel: 'Переименовать',
    renameDialogTitle: 'Переименовать разговор',
    renameFieldLabel: 'Название разговора',
    renameFieldPlaceholder: 'Введите название разговора.',
    renameCancelLabel: 'Отмена',
    renameConfirmLabel: 'Сохранить',
    renamingLabel: 'Сохранение...',
    renameEmptyMessage: 'Введите название разговора.',
    renameSuccessToastLabel: 'Название разговора обновлено.',
    renameErrorToastLabel: 'Не удалось обновить название разговора. Повторите попытку позже.',
  },
  ar: {
    menuItemLabel: 'إدارة المحادثة',
    pageTitle: 'إدارة المحادثة',
    backButtonLabel: 'رجوع',
    renameButtonLabel: 'إعادة تسمية',
    renameDialogTitle: 'تغيير اسم المحادثة',
    renameFieldLabel: 'اسم المحادثة',
    renameFieldPlaceholder: 'أدخل اسم المحادثة.',
    renameCancelLabel: 'إلغاء',
    renameConfirmLabel: 'حفظ',
    renamingLabel: 'جارٍ الحفظ...',
    renameEmptyMessage: 'يرجى إدخال اسم المحادثة.',
    renameSuccessToastLabel: 'تم تحديث اسم المحادثة.',
    renameErrorToastLabel: 'تعذر تحديث اسم المحادثة. يرجى المحاولة مرة أخرى لاحقًا.',
  },
  hi: {
    menuItemLabel: 'बातचीत प्रबंधन',
    pageTitle: 'बातचीत प्रबंधन',
    backButtonLabel: 'वापस',
    renameButtonLabel: 'नाम बदलें',
    renameDialogTitle: 'बातचीत का नाम बदलें',
    renameFieldLabel: 'बातचीत का नाम',
    renameFieldPlaceholder: 'बातचीत का नाम दर्ज करें।',
    renameCancelLabel: 'रद्द करें',
    renameConfirmLabel: 'सहेजें',
    renamingLabel: 'सहेजा जा रहा है...',
    renameEmptyMessage: 'कृपया बातचीत का नाम दर्ज करें।',
    renameSuccessToastLabel: 'बातचीत का नाम अपडेट हो गया।',
    renameErrorToastLabel: 'बातचीत का नाम अपडेट नहीं हो सका। कृपया फिर से प्रयास करें।',
  },
  th: {
    menuItemLabel: 'จัดการห้องสนทนา',
    pageTitle: 'จัดการห้องสนทนา',
    backButtonLabel: 'ย้อนกลับ',
    renameButtonLabel: 'เปลี่ยนชื่อห้องสนทนา',
    renameDialogTitle: 'เปลี่ยนชื่อห้องสนทนา',
    renameFieldLabel: 'ชื่อห้องสนทนา',
    renameFieldPlaceholder: 'กรอกชื่อห้องสนทนา',
    renameCancelLabel: 'ยกเลิก',
    renameConfirmLabel: 'บันทึก',
    renamingLabel: 'กำลังบันทึก...',
    renameEmptyMessage: 'กรุณากรอกชื่อห้องสนทนา',
    renameSuccessToastLabel: 'อัปเดตชื่อห้องสนทนาแล้ว',
    renameErrorToastLabel: 'ไม่สามารถอัปเดตชื่อห้องสนทนาได้ โปรดลองอีกครั้ง',
  },
  vi: {
    menuItemLabel: 'Quan ly cuoc tro chuyen',
    pageTitle: 'Quan ly cuoc tro chuyen',
    backButtonLabel: 'Quay lai',
    renameButtonLabel: 'Doi ten',
    renameDialogTitle: 'Doi ten cuoc tro chuyen',
    renameFieldLabel: 'Ten cuoc tro chuyen',
    renameFieldPlaceholder: 'Nhap ten cuoc tro chuyen.',
    renameCancelLabel: 'Huy',
    renameConfirmLabel: 'Luu',
    renamingLabel: 'Dang luu...',
    renameEmptyMessage: 'Vui long nhap ten cuoc tro chuyen.',
    renameSuccessToastLabel: 'Da cap nhat ten cuoc tro chuyen.',
    renameErrorToastLabel: 'Khong the cap nhat ten cuoc tro chuyen. Vui long thu lai.',
  },
} satisfies Record<LegalDocumentLocale, LivePhoneDemoRoomManagementCopy>

export function resolveLivePhoneDemoRoomManagementCopy(
  uiLocale: string,
): LivePhoneDemoRoomManagementCopy {
  const supportedLocale = resolveSupportedLocaleTag(uiLocale) ?? DEFAULT_LOCALE
  const resolvedLocale = resolveLegalDocumentLocale(supportedLocale)

  return ROOM_MANAGEMENT_COPY_BY_LOCALE[resolvedLocale] ?? ROOM_MANAGEMENT_COPY_BY_LOCALE.en
}
