import {
  DEFAULT_LOCALE,
  resolveLegalDocumentLocale,
  resolveSupportedLocaleTag,
  type LegalDocumentLocale,
} from '@/i18n/config'

export type LivePhoneDemoRoomManagementCopy = {
  menuItemLabel: string
  pageTitle: string
  backButtonLabel: string
  languageSelectorTitle: string
  languageSelectorDescription: string
  languageSelectorCloseLabel: string
  languageSelectorSearchPlaceholder: string
  languageSelectorSortLocaleLabel: string
  languageSelectorSortAlphabeticalLabel: string
  languageSelectorNoResultsLabel: string
  renameButtonLabel: string
  renameDialogTitle: string
  renameFieldLabel: string
  renameFieldPlaceholder: string
  renameCancelLabel: string
  renameConfirmLabel: string
  renamingLabel: string
  renameEmptyMessage: string
  renameSuccessToastLabel: string
  renameErrorToastLabel: string
  defaultDisplayLanguageMenuItemLabel: string
  defaultDisplayLanguagePageTitle: string
  participantsMenuItemLabel: string
  participantsPageTitle: string
  participantsSelfLabel: string
  participantsLoadingLabel: string
  participantsErrorLabel: string
  participantsRetryLabel: string
  participantsInviteButtonLabel: string
  shareToggleLabel: string
  shareToggleDescription: string
  shareEnabledToastLabel: string
  shareDisabledToastLabel: string
  shareRefreshButtonLabel: string
  shareRefreshedToastLabel: string
  shareLinkCopyButtonLabel: string
  shareLinkCopiedToastLabel: string
  shareErrorToastLabel: string
}

const ROOM_MANAGEMENT_COPY_BY_LOCALE = {
  ko: {
    menuItemLabel: '대화방 관리',
    pageTitle: '대화방 관리',
    backButtonLabel: '뒤로가기',
    languageSelectorTitle: '번역 언어 선택',
    languageSelectorDescription: '여러 언어를 선택해도 여러 언어로 동시에 번역합니다.',
    languageSelectorCloseLabel: '닫기',
    languageSelectorSearchPlaceholder: '언어 검색',
    languageSelectorSortLocaleLabel: '가나다',
    languageSelectorSortAlphabeticalLabel: 'A-Z',
    languageSelectorNoResultsLabel: '검색 결과가 없어요.',
    renameButtonLabel: '대화방 이름 변경',
    renameDialogTitle: '대화방 이름 변경',
    renameFieldLabel: '대화방 이름',
    renameFieldPlaceholder: '대화방 이름을 입력해 주세요.',
    renameCancelLabel: '취소',
    renameConfirmLabel: '저장',
    renamingLabel: '저장 중...',
    renameEmptyMessage: '대화방 이름을 입력해 주세요.',
    renameSuccessToastLabel: '대화방 이름이 변경되었습니다.',
    renameErrorToastLabel: '대화방 이름 변경에 실패했습니다. 잠시 후 다시 시도해 주세요.',
    defaultDisplayLanguageMenuItemLabel: '디폴트 표시 언어',
    defaultDisplayLanguagePageTitle: '디폴트 표시 언어',
    participantsMenuItemLabel: '참여자',
    participantsPageTitle: '참여자',
    participantsSelfLabel: '나',
    participantsLoadingLabel: '불러오는 중...',
    participantsErrorLabel: '참여자 정보를 불러오지 못했습니다.',
    participantsRetryLabel: '다시 시도',
    participantsInviteButtonLabel: '초대',
    shareToggleLabel: '대화방 공유',
    shareToggleDescription: '켜면 누구나 링크로 이 대화방을 볼 수 있어요. 메시지를 보내거나 참여할 수는 없어요.',
    shareEnabledToastLabel: '대화방이 공유되었습니다.',
    shareDisabledToastLabel: '공유가 중지되었습니다.',
    shareRefreshButtonLabel: '공유 링크 새로고침',
    shareRefreshedToastLabel: '공유 링크를 새로고침했습니다.',
    shareLinkCopyButtonLabel: '링크 복사',
    shareLinkCopiedToastLabel: '링크가 복사되었습니다.',
    shareErrorToastLabel: '공유 설정을 변경하지 못했습니다. 잠시 후 다시 시도해 주세요.',
  },
  en: {
    menuItemLabel: 'Conversation management',
    pageTitle: 'Conversation management',
    backButtonLabel: 'Go back',
    languageSelectorTitle: 'Select Target Languages',
    languageSelectorDescription: 'Select multiple languages to translate into all of them at the same time.',
    languageSelectorCloseLabel: 'Close',
    languageSelectorSearchPlaceholder: 'Search languages',
    languageSelectorSortLocaleLabel: 'A-Z',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'No languages found.',
    renameButtonLabel: 'Rename',
    renameDialogTitle: 'Rename conversation',
    renameFieldLabel: 'Conversation name',
    renameFieldPlaceholder: 'Enter a conversation name.',
    renameCancelLabel: 'Cancel',
    renameConfirmLabel: 'Save',
    renamingLabel: 'Saving...',
    renameEmptyMessage: 'Please enter a conversation name.',
    renameSuccessToastLabel: 'The conversation name was updated.',
    renameErrorToastLabel: 'Failed to update the conversation name. Please try again.',
    defaultDisplayLanguageMenuItemLabel: 'Default display language',
    defaultDisplayLanguagePageTitle: 'Default display language',
    participantsMenuItemLabel: 'Participants',
    participantsPageTitle: 'Participants',
    participantsSelfLabel: 'You',
    participantsLoadingLabel: 'Loading...',
    participantsErrorLabel: 'Could not load participants.',
    participantsRetryLabel: 'Try again',
    participantsInviteButtonLabel: 'Invite',
    shareToggleLabel: 'Share this conversation',
    shareToggleDescription: 'When on, anyone with the link can view this conversation. They can’t send messages or join.',
    shareEnabledToastLabel: 'This conversation is now shared.',
    shareDisabledToastLabel: 'Sharing turned off.',
    shareRefreshButtonLabel: 'Refresh share link',
    shareRefreshedToastLabel: 'Share link refreshed.',
    shareLinkCopyButtonLabel: 'Copy link',
    shareLinkCopiedToastLabel: 'Link copied.',
    shareErrorToastLabel: 'Could not update sharing. Please try again.',
  },
  ja: {
    menuItemLabel: '会話ルーム管理',
    pageTitle: '会話ルーム管理',
    backButtonLabel: '戻る',
    languageSelectorTitle: '翻訳言語を選択',
    languageSelectorDescription: '複数の言語を選択すると、すべての言語に同時に翻訳します。',
    languageSelectorCloseLabel: '閉じる',
    languageSelectorSearchPlaceholder: '言語を検索',
    languageSelectorSortLocaleLabel: 'あいう',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: '一致する言語がありません。',
    renameButtonLabel: '会話名を変更',
    renameDialogTitle: '会話名を変更',
    renameFieldLabel: '会話名',
    renameFieldPlaceholder: '会話名を入力してください。',
    renameCancelLabel: 'キャンセル',
    renameConfirmLabel: '保存',
    renamingLabel: '保存中...',
    renameEmptyMessage: '会話名を入力してください。',
    renameSuccessToastLabel: '会話名を変更しました。',
    renameErrorToastLabel: '会話名を変更できませんでした。しばらくしてからもう一度お試しください。',
    defaultDisplayLanguageMenuItemLabel: 'デフォルト表示言語',
    defaultDisplayLanguagePageTitle: 'デフォルト表示言語',
    participantsMenuItemLabel: '参加者',
    participantsPageTitle: '参加者',
    participantsSelfLabel: '自分',
    participantsLoadingLabel: '読み込み中...',
    participantsErrorLabel: '参加者情報を読み込めませんでした。',
    participantsRetryLabel: '再試行',
    participantsInviteButtonLabel: '招待',
    shareToggleLabel: '会話ルームを共有',
    shareToggleDescription: 'オンにすると、リンクを知っている人なら誰でもこの会話を見られます。メッセージの送信や参加はできません。',
    shareEnabledToastLabel: '会話ルームを共有しました。',
    shareDisabledToastLabel: '共有を停止しました。',
    shareRefreshButtonLabel: '共有リンクを更新',
    shareRefreshedToastLabel: '共有リンクを更新しました。',
    shareLinkCopyButtonLabel: 'リンクをコピー',
    shareLinkCopiedToastLabel: 'リンクをコピーしました。',
    shareErrorToastLabel: '共有設定を変更できませんでした。しばらくしてからもう一度お試しください。',
  },
  'zh-CN': {
    menuItemLabel: '会话房间管理',
    pageTitle: '会话房间管理',
    backButtonLabel: '返回',
    languageSelectorTitle: '选择翻译语言',
    languageSelectorDescription: '选择多种语言后，我们会同时翻译成这些语言。',
    languageSelectorCloseLabel: '关闭',
    languageSelectorSearchPlaceholder: '搜索语言',
    languageSelectorSortLocaleLabel: '中文顺序',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: '没有找到匹配的语言。',
    renameButtonLabel: '修改会话名称',
    renameDialogTitle: '修改会话名称',
    renameFieldLabel: '会话名称',
    renameFieldPlaceholder: '请输入会话名称。',
    renameCancelLabel: '取消',
    renameConfirmLabel: '保存',
    renamingLabel: '保存中...',
    renameEmptyMessage: '请输入会话名称。',
    renameSuccessToastLabel: '会话名称已更新。',
    renameErrorToastLabel: '更新会话名称失败。请稍后再试。',
    defaultDisplayLanguageMenuItemLabel: '默认显示语言',
    defaultDisplayLanguagePageTitle: '默认显示语言',
    participantsMenuItemLabel: '参与者',
    participantsPageTitle: '参与者',
    participantsSelfLabel: '你',
    participantsLoadingLabel: '加载中...',
    participantsErrorLabel: '无法加载参与者信息。',
    participantsRetryLabel: '重试',
    participantsInviteButtonLabel: '邀请',
    shareToggleLabel: '共享此会话',
    shareToggleDescription: '开启后，任何拥有链接的人都可以查看此会话，但不能发送消息或加入。',
    shareEnabledToastLabel: '会话已共享。',
    shareDisabledToastLabel: '已停止共享。',
    shareRefreshButtonLabel: '刷新共享链接',
    shareRefreshedToastLabel: '共享链接已刷新。',
    shareLinkCopyButtonLabel: '复制链接',
    shareLinkCopiedToastLabel: '链接已复制。',
    shareErrorToastLabel: '无法更新共享设置。请稍后再试。',
  },
  'zh-TW': {
    menuItemLabel: '對話房間管理',
    pageTitle: '對話房間管理',
    backButtonLabel: '返回',
    languageSelectorTitle: '選擇翻譯語言',
    languageSelectorDescription: '選擇多種語言後，我們會同時翻譯成這些語言。',
    languageSelectorCloseLabel: '關閉',
    languageSelectorSearchPlaceholder: '搜尋語言',
    languageSelectorSortLocaleLabel: '中文順序',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: '找不到符合的語言。',
    renameButtonLabel: '變更對話名稱',
    renameDialogTitle: '變更對話名稱',
    renameFieldLabel: '對話名稱',
    renameFieldPlaceholder: '請輸入對話名稱。',
    renameCancelLabel: '取消',
    renameConfirmLabel: '儲存',
    renamingLabel: '儲存中...',
    renameEmptyMessage: '請輸入對話名稱。',
    renameSuccessToastLabel: '對話名稱已更新。',
    renameErrorToastLabel: '更新對話名稱失敗。請稍後再試。',
    defaultDisplayLanguageMenuItemLabel: '預設顯示語言',
    defaultDisplayLanguagePageTitle: '預設顯示語言',
    participantsMenuItemLabel: '參與者',
    participantsPageTitle: '參與者',
    participantsSelfLabel: '你',
    participantsLoadingLabel: '載入中...',
    participantsErrorLabel: '無法載入參與者資訊。',
    participantsRetryLabel: '重試',
    participantsInviteButtonLabel: '邀請',
    shareToggleLabel: '共享此對話',
    shareToggleDescription: '開啟後，任何擁有連結的人都可以查看此對話，但不能發送訊息或加入。',
    shareEnabledToastLabel: '對話已共享。',
    shareDisabledToastLabel: '已停止共享。',
    shareRefreshButtonLabel: '重新整理共享連結',
    shareRefreshedToastLabel: '共享連結已重新整理。',
    shareLinkCopyButtonLabel: '複製連結',
    shareLinkCopiedToastLabel: '連結已複製。',
    shareErrorToastLabel: '無法更新共享設定。請稍後再試。',
  },
  fr: {
    menuItemLabel: 'Gestion de la conversation',
    pageTitle: 'Gestion de la conversation',
    backButtonLabel: 'Retour',
    languageSelectorTitle: 'Sélectionner les langues cibles',
    languageSelectorDescription: 'Sélectionnez plusieurs langues pour traduire dans toutes ces langues en même temps.',
    languageSelectorCloseLabel: 'Fermer',
    languageSelectorSearchPlaceholder: 'Rechercher une langue',
    languageSelectorSortLocaleLabel: 'A-Z',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'Aucune langue correspondante.',
    renameButtonLabel: 'Renommer',
    renameDialogTitle: 'Renommer la conversation',
    renameFieldLabel: 'Nom de la conversation',
    renameFieldPlaceholder: 'Saisissez un nom de conversation.',
    renameCancelLabel: 'Annuler',
    renameConfirmLabel: 'Enregistrer',
    renamingLabel: 'Enregistrement...',
    renameEmptyMessage: 'Veuillez saisir un nom de conversation.',
    renameSuccessToastLabel: 'Le nom de la conversation a ete mis a jour.',
    renameErrorToastLabel: "Impossible de modifier le nom de la conversation. Veuillez reessayer.",
    defaultDisplayLanguageMenuItemLabel: 'Langue d’affichage par défaut',
    defaultDisplayLanguagePageTitle: 'Langue d’affichage par défaut',
    participantsMenuItemLabel: 'Participants',
    participantsPageTitle: 'Participants',
    participantsSelfLabel: 'Vous',
    participantsLoadingLabel: 'Chargement...',
    participantsErrorLabel: 'Impossible de charger les participants.',
    participantsRetryLabel: 'Réessayer',
    participantsInviteButtonLabel: 'Inviter',
    shareToggleLabel: 'Partager cette conversation',
    shareToggleDescription: 'Une fois activé, toute personne disposant du lien peut voir cette conversation. Elle ne peut pas envoyer de messages ni la rejoindre.',
    shareEnabledToastLabel: 'Cette conversation est maintenant partagée.',
    shareDisabledToastLabel: 'Le partage a été désactivé.',
    shareRefreshButtonLabel: 'Actualiser le lien de partage',
    shareRefreshedToastLabel: 'Lien de partage actualisé.',
    shareLinkCopyButtonLabel: 'Copier le lien',
    shareLinkCopiedToastLabel: 'Lien copié.',
    shareErrorToastLabel: 'Impossible de mettre à jour le partage. Veuillez réessayer.',
  },
  de: {
    menuItemLabel: 'Verwaltung des Gesprächs',
    pageTitle: 'Verwaltung des Gesprächs',
    backButtonLabel: 'Zurück',
    languageSelectorTitle: 'Zielsprachen auswählen',
    languageSelectorDescription: 'Wählen Sie mehrere Sprachen aus, um gleichzeitig in alle zu übersetzen.',
    languageSelectorCloseLabel: 'Schließen',
    languageSelectorSearchPlaceholder: 'Sprache suchen',
    languageSelectorSortLocaleLabel: 'A-Z',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'Keine passende Sprache gefunden.',
    renameButtonLabel: 'Umbenennen',
    renameDialogTitle: 'Gesprach umbenennen',
    renameFieldLabel: 'Gesprachsname',
    renameFieldPlaceholder: 'Geben Sie einen Gesprachsnamen ein.',
    renameCancelLabel: 'Abbrechen',
    renameConfirmLabel: 'Speichern',
    renamingLabel: 'Wird gespeichert...',
    renameEmptyMessage: 'Bitte geben Sie einen Gesprachsnamen ein.',
    renameSuccessToastLabel: 'Der Gesprachsname wurde aktualisiert.',
    renameErrorToastLabel: 'Der Gesprachsname konnte nicht aktualisiert werden. Bitte versuchen Sie es erneut.',
    defaultDisplayLanguageMenuItemLabel: 'Standard-Anzeigesprache',
    defaultDisplayLanguagePageTitle: 'Standard-Anzeigesprache',
    participantsMenuItemLabel: 'Teilnehmer',
    participantsPageTitle: 'Teilnehmer',
    participantsSelfLabel: 'Du',
    participantsLoadingLabel: 'Wird geladen...',
    participantsErrorLabel: 'Teilnehmer konnten nicht geladen werden.',
    participantsRetryLabel: 'Erneut versuchen',
    participantsInviteButtonLabel: 'Einladen',
    shareToggleLabel: 'Diese Unterhaltung teilen',
    shareToggleDescription: 'Wenn aktiviert, kann jeder mit dem Link diese Unterhaltung ansehen. Nachrichten senden oder teilnehmen ist nicht möglich.',
    shareEnabledToastLabel: 'Diese Unterhaltung wird jetzt geteilt.',
    shareDisabledToastLabel: 'Teilen wurde deaktiviert.',
    shareRefreshButtonLabel: 'Freigabelink aktualisieren',
    shareRefreshedToastLabel: 'Freigabelink aktualisiert.',
    shareLinkCopyButtonLabel: 'Link kopieren',
    shareLinkCopiedToastLabel: 'Link kopiert.',
    shareErrorToastLabel: 'Teilen konnte nicht aktualisiert werden. Bitte versuchen Sie es erneut.',
  },
  es: {
    menuItemLabel: 'Gestion de la conversacion',
    pageTitle: 'Gestion de la conversacion',
    backButtonLabel: 'Volver',
    languageSelectorTitle: 'Seleccionar idiomas de destino',
    languageSelectorDescription: 'Selecciona varios idiomas para traducir a todos al mismo tiempo.',
    languageSelectorCloseLabel: 'Cerrar',
    languageSelectorSearchPlaceholder: 'Buscar idioma',
    languageSelectorSortLocaleLabel: 'A-Z',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'No se encontró ningún idioma.',
    renameButtonLabel: 'Renombrar',
    renameDialogTitle: 'Cambiar nombre de la conversacion',
    renameFieldLabel: 'Nombre de la conversacion',
    renameFieldPlaceholder: 'Introduce un nombre para la conversacion.',
    renameCancelLabel: 'Cancelar',
    renameConfirmLabel: 'Guardar',
    renamingLabel: 'Guardando...',
    renameEmptyMessage: 'Introduce un nombre para la conversacion.',
    renameSuccessToastLabel: 'Se actualizo el nombre de la conversacion.',
    renameErrorToastLabel: 'No se pudo actualizar el nombre de la conversacion. Intentalo de nuevo.',
    defaultDisplayLanguageMenuItemLabel: 'Idioma de visualización predeterminado',
    defaultDisplayLanguagePageTitle: 'Idioma de visualización predeterminado',
    participantsMenuItemLabel: 'Participantes',
    participantsPageTitle: 'Participantes',
    participantsSelfLabel: 'Tú',
    participantsLoadingLabel: 'Cargando...',
    participantsErrorLabel: 'No se pudieron cargar los participantes.',
    participantsRetryLabel: 'Intentar de nuevo',
    participantsInviteButtonLabel: 'Invitar',
    shareToggleLabel: 'Compartir esta conversación',
    shareToggleDescription: 'Al activarlo, cualquiera con el enlace podrá ver esta conversación. No podrá enviar mensajes ni unirse.',
    shareEnabledToastLabel: 'Esta conversación ahora se comparte.',
    shareDisabledToastLabel: 'Se desactivó el uso compartido.',
    shareRefreshButtonLabel: 'Actualizar enlace para compartir',
    shareRefreshedToastLabel: 'Enlace para compartir actualizado.',
    shareLinkCopyButtonLabel: 'Copiar enlace',
    shareLinkCopiedToastLabel: 'Enlace copiado.',
    shareErrorToastLabel: 'No se pudo actualizar el uso compartido. Intentalo de nuevo.',
  },
  pt: {
    menuItemLabel: 'Gerenciamento da conversa',
    pageTitle: 'Gerenciamento da conversa',
    backButtonLabel: 'Voltar',
    languageSelectorTitle: 'Selecionar idiomas de destino',
    languageSelectorDescription: 'Selecione vários idiomas para traduzir para todos ao mesmo tempo.',
    languageSelectorCloseLabel: 'Fechar',
    languageSelectorSearchPlaceholder: 'Buscar idioma',
    languageSelectorSortLocaleLabel: 'A-Z',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'Nenhum idioma encontrado.',
    renameButtonLabel: 'Renomear',
    renameDialogTitle: 'Renomear conversa',
    renameFieldLabel: 'Nome da conversa',
    renameFieldPlaceholder: 'Digite um nome para a conversa.',
    renameCancelLabel: 'Cancelar',
    renameConfirmLabel: 'Salvar',
    renamingLabel: 'Salvando...',
    renameEmptyMessage: 'Digite um nome para a conversa.',
    renameSuccessToastLabel: 'O nome da conversa foi atualizado.',
    renameErrorToastLabel: 'Nao foi possivel atualizar o nome da conversa. Tente novamente.',
    defaultDisplayLanguageMenuItemLabel: 'Idioma de exibição padrão',
    defaultDisplayLanguagePageTitle: 'Idioma de exibição padrão',
    participantsMenuItemLabel: 'Participantes',
    participantsPageTitle: 'Participantes',
    participantsSelfLabel: 'Você',
    participantsLoadingLabel: 'Carregando...',
    participantsErrorLabel: 'Não foi possível carregar os participantes.',
    participantsRetryLabel: 'Tentar novamente',
    participantsInviteButtonLabel: 'Convidar',
    shareToggleLabel: 'Compartilhar esta conversa',
    shareToggleDescription: 'Quando ativado, qualquer pessoa com o link pode ver esta conversa. Ela não pode enviar mensagens ou entrar.',
    shareEnabledToastLabel: 'Esta conversa agora está compartilhada.',
    shareDisabledToastLabel: 'O compartilhamento foi desativado.',
    shareRefreshButtonLabel: 'Atualizar link de compartilhamento',
    shareRefreshedToastLabel: 'Link de compartilhamento atualizado.',
    shareLinkCopyButtonLabel: 'Copiar link',
    shareLinkCopiedToastLabel: 'Link copiado.',
    shareErrorToastLabel: 'Não foi possível atualizar o compartilhamento. Tente novamente.',
  },
  it: {
    menuItemLabel: 'Gestione della conversazione',
    pageTitle: 'Gestione della conversazione',
    backButtonLabel: 'Indietro',
    languageSelectorTitle: 'Seleziona le lingue di destinazione',
    languageSelectorDescription: 'Seleziona più lingue per tradurre in tutte contemporaneamente.',
    languageSelectorCloseLabel: 'Chiudi',
    languageSelectorSearchPlaceholder: 'Cerca una lingua',
    languageSelectorSortLocaleLabel: 'A-Z',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'Nessuna lingua trovata.',
    renameButtonLabel: 'Rinomina',
    renameDialogTitle: 'Rinomina conversazione',
    renameFieldLabel: 'Nome della conversazione',
    renameFieldPlaceholder: 'Inserisci un nome per la conversazione.',
    renameCancelLabel: 'Annulla',
    renameConfirmLabel: 'Salva',
    renamingLabel: 'Salvataggio...',
    renameEmptyMessage: 'Inserisci un nome per la conversazione.',
    renameSuccessToastLabel: 'Il nome della conversazione e stato aggiornato.',
    renameErrorToastLabel: 'Impossibile aggiornare il nome della conversazione. Riprova.',
    defaultDisplayLanguageMenuItemLabel: 'Lingua di visualizzazione predefinita',
    defaultDisplayLanguagePageTitle: 'Lingua di visualizzazione predefinita',
    participantsMenuItemLabel: 'Partecipanti',
    participantsPageTitle: 'Partecipanti',
    participantsSelfLabel: 'Tu',
    participantsLoadingLabel: 'Caricamento...',
    participantsErrorLabel: 'Impossibile caricare i partecipanti.',
    participantsRetryLabel: 'Riprova',
    participantsInviteButtonLabel: 'Invita',
    shareToggleLabel: 'Condividi questa conversazione',
    shareToggleDescription: 'Se attivo, chiunque abbia il link può vedere questa conversazione. Non può inviare messaggi né partecipare.',
    shareEnabledToastLabel: 'Questa conversazione è ora condivisa.',
    shareDisabledToastLabel: 'Condivisione disattivata.',
    shareRefreshButtonLabel: 'Aggiorna link di condivisione',
    shareRefreshedToastLabel: 'Link di condivisione aggiornato.',
    shareLinkCopyButtonLabel: 'Copia link',
    shareLinkCopiedToastLabel: 'Link copiato.',
    shareErrorToastLabel: 'Impossibile aggiornare la condivisione. Riprova.',
  },
  ru: {
    menuItemLabel: 'Управление разговором',
    pageTitle: 'Управление разговором',
    backButtonLabel: 'Назад',
    languageSelectorTitle: 'Выбрать языки перевода',
    languageSelectorDescription: 'Выберите несколько языков, чтобы переводить на них одновременно.',
    languageSelectorCloseLabel: 'Закрыть',
    languageSelectorSearchPlaceholder: 'Поиск языка',
    languageSelectorSortLocaleLabel: 'А-Я',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'Подходящий язык не найден.',
    renameButtonLabel: 'Переименовать',
    renameDialogTitle: 'Переименовать разговор',
    renameFieldLabel: 'Название разговора',
    renameFieldPlaceholder: 'Введите название разговора.',
    renameCancelLabel: 'Отмена',
    renameConfirmLabel: 'Сохранить',
    renamingLabel: 'Сохранение...',
    renameEmptyMessage: 'Введите название разговора.',
    renameSuccessToastLabel: 'Название разговора обновлено.',
    renameErrorToastLabel: 'Не удалось обновить название разговора. Повторите попытку позже.',
    defaultDisplayLanguageMenuItemLabel: 'Язык отображения по умолчанию',
    defaultDisplayLanguagePageTitle: 'Язык отображения по умолчанию',
    participantsMenuItemLabel: 'Участники',
    participantsPageTitle: 'Участники',
    participantsSelfLabel: 'Вы',
    participantsLoadingLabel: 'Загрузка...',
    participantsErrorLabel: 'Не удалось загрузить участников.',
    participantsRetryLabel: 'Повторить',
    participantsInviteButtonLabel: 'Пригласить',
    shareToggleLabel: 'Поделиться разговором',
    shareToggleDescription: 'Если включено, любой, у кого есть ссылка, сможет просматривать этот разговор. Отправлять сообщения или присоединяться нельзя.',
    shareEnabledToastLabel: 'Этот разговор теперь доступен по ссылке.',
    shareDisabledToastLabel: 'Общий доступ отключён.',
    shareRefreshButtonLabel: 'Обновить ссылку для общего доступа',
    shareRefreshedToastLabel: 'Ссылка для общего доступа обновлена.',
    shareLinkCopyButtonLabel: 'Скопировать ссылку',
    shareLinkCopiedToastLabel: 'Ссылка скопирована.',
    shareErrorToastLabel: 'Не удалось изменить настройки доступа. Повторите попытку позже.',
  },
  ar: {
    menuItemLabel: 'إدارة المحادثة',
    pageTitle: 'إدارة المحادثة',
    backButtonLabel: 'رجوع',
    languageSelectorTitle: 'اختيار لغات الترجمة',
    languageSelectorDescription: 'اختر عدة لغات للترجمة إليها جميعًا في الوقت نفسه.',
    languageSelectorCloseLabel: 'إغلاق',
    languageSelectorSearchPlaceholder: 'ابحث عن لغة',
    languageSelectorSortLocaleLabel: 'أ-ي',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'لم يتم العثور على لغة مطابقة.',
    renameButtonLabel: 'إعادة تسمية',
    renameDialogTitle: 'تغيير اسم المحادثة',
    renameFieldLabel: 'اسم المحادثة',
    renameFieldPlaceholder: 'أدخل اسم المحادثة.',
    renameCancelLabel: 'إلغاء',
    renameConfirmLabel: 'حفظ',
    renamingLabel: 'جارٍ الحفظ...',
    renameEmptyMessage: 'يرجى إدخال اسم المحادثة.',
    renameSuccessToastLabel: 'تم تحديث اسم المحادثة.',
    renameErrorToastLabel: 'تعذر تحديث اسم المحادثة. يرجى المحاولة مرة أخرى لاحقًا.',
    defaultDisplayLanguageMenuItemLabel: 'لغة العرض الافتراضية',
    defaultDisplayLanguagePageTitle: 'لغة العرض الافتراضية',
    participantsMenuItemLabel: 'المشاركون',
    participantsPageTitle: 'المشاركون',
    participantsSelfLabel: 'أنت',
    participantsLoadingLabel: 'جارٍ التحميل...',
    participantsErrorLabel: 'تعذر تحميل المشاركين.',
    participantsRetryLabel: 'إعادة المحاولة',
    participantsInviteButtonLabel: 'دعوة',
    shareToggleLabel: 'مشاركة هذه المحادثة',
    shareToggleDescription: 'عند التفعيل، يمكن لأي شخص لديه الرابط عرض هذه المحادثة. لا يمكنه إرسال رسائل أو الانضمام.',
    shareEnabledToastLabel: 'تتم الآن مشاركة هذه المحادثة.',
    shareDisabledToastLabel: 'تم إيقاف المشاركة.',
    shareRefreshButtonLabel: 'تحديث رابط المشاركة',
    shareRefreshedToastLabel: 'تم تحديث رابط المشاركة.',
    shareLinkCopyButtonLabel: 'نسخ الرابط',
    shareLinkCopiedToastLabel: 'تم نسخ الرابط.',
    shareErrorToastLabel: 'تعذر تحديث إعدادات المشاركة. يرجى المحاولة مرة أخرى لاحقًا.',
  },
  hi: {
    menuItemLabel: 'बातचीत प्रबंधन',
    pageTitle: 'बातचीत प्रबंधन',
    backButtonLabel: 'वापस',
    languageSelectorTitle: 'अनुवाद भाषाएँ चुनें',
    languageSelectorDescription: 'कई भाषाएँ चुनें और सभी में एक साथ अनुवाद पाएँ।',
    languageSelectorCloseLabel: 'बंद करें',
    languageSelectorSearchPlaceholder: 'भाषा खोजें',
    languageSelectorSortLocaleLabel: 'अ-ह',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'मिलती-जुलती भाषा नहीं मिली।',
    renameButtonLabel: 'नाम बदलें',
    renameDialogTitle: 'बातचीत का नाम बदलें',
    renameFieldLabel: 'बातचीत का नाम',
    renameFieldPlaceholder: 'बातचीत का नाम दर्ज करें।',
    renameCancelLabel: 'रद्द करें',
    renameConfirmLabel: 'सहेजें',
    renamingLabel: 'सहेजा जा रहा है...',
    renameEmptyMessage: 'कृपया बातचीत का नाम दर्ज करें।',
    renameSuccessToastLabel: 'बातचीत का नाम अपडेट हो गया।',
    renameErrorToastLabel: 'बातचीत का नाम अपडेट नहीं हो सका। कृपया फिर से प्रयास करें।',
    defaultDisplayLanguageMenuItemLabel: 'डिफ़ॉल्ट प्रदर्शन भाषा',
    defaultDisplayLanguagePageTitle: 'डिफ़ॉल्ट प्रदर्शन भाषा',
    participantsMenuItemLabel: 'प्रतिभागी',
    participantsPageTitle: 'प्रतिभागी',
    participantsSelfLabel: 'आप',
    participantsLoadingLabel: 'लोड हो रहा है...',
    participantsErrorLabel: 'प्रतिभागियों को लोड नहीं किया जा सका।',
    participantsRetryLabel: 'फिर से कोशिश करें',
    participantsInviteButtonLabel: 'आमंत्रित करें',
    shareToggleLabel: 'यह बातचीत शेयर करें',
    shareToggleDescription: 'चालू करने पर, लिंक रखने वाला कोई भी व्यक्ति इस बातचीत को देख सकता है। वह मैसेज नहीं भेज सकता या शामिल नहीं हो सकता।',
    shareEnabledToastLabel: 'यह बातचीत अब शेयर की गई है।',
    shareDisabledToastLabel: 'शेयरिंग बंद कर दी गई।',
    shareRefreshButtonLabel: 'शेयर लिंक रीफ्रेश करें',
    shareRefreshedToastLabel: 'शेयर लिंक रीफ्रेश हो गया।',
    shareLinkCopyButtonLabel: 'लिंक कॉपी करें',
    shareLinkCopiedToastLabel: 'लिंक कॉपी हो गया।',
    shareErrorToastLabel: 'शेयरिंग सेटिंग अपडेट नहीं हो सकी। कृपया फिर से प्रयास करें।',
  },
  th: {
    menuItemLabel: 'จัดการห้องสนทนา',
    pageTitle: 'จัดการห้องสนทนา',
    backButtonLabel: 'ย้อนกลับ',
    languageSelectorTitle: 'เลือกภาษาที่ต้องการแปล',
    languageSelectorDescription: 'เลือกหลายภาษาเพื่อแปลเป็นทุกภาษาได้พร้อมกัน',
    languageSelectorCloseLabel: 'ปิด',
    languageSelectorSearchPlaceholder: 'ค้นหาภาษา',
    languageSelectorSortLocaleLabel: 'ก-ฮ',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'ไม่พบภาษาที่ตรงกัน',
    renameButtonLabel: 'เปลี่ยนชื่อห้องสนทนา',
    renameDialogTitle: 'เปลี่ยนชื่อห้องสนทนา',
    renameFieldLabel: 'ชื่อห้องสนทนา',
    renameFieldPlaceholder: 'กรอกชื่อห้องสนทนา',
    renameCancelLabel: 'ยกเลิก',
    renameConfirmLabel: 'บันทึก',
    renamingLabel: 'กำลังบันทึก...',
    renameEmptyMessage: 'กรุณากรอกชื่อห้องสนทนา',
    renameSuccessToastLabel: 'อัปเดตชื่อห้องสนทนาแล้ว',
    renameErrorToastLabel: 'ไม่สามารถอัปเดตชื่อห้องสนทนาได้ โปรดลองอีกครั้ง',
    defaultDisplayLanguageMenuItemLabel: 'ภาษาที่แสดงเริ่มต้น',
    defaultDisplayLanguagePageTitle: 'ภาษาที่แสดงเริ่มต้น',
    participantsMenuItemLabel: 'ผู้เข้าร่วม',
    participantsPageTitle: 'ผู้เข้าร่วม',
    participantsSelfLabel: 'คุณ',
    participantsLoadingLabel: 'กำลังโหลด...',
    participantsErrorLabel: 'ไม่สามารถโหลดข้อมูลผู้เข้าร่วมได้',
    participantsRetryLabel: 'ลองอีกครั้ง',
    participantsInviteButtonLabel: 'เชิญ',
    shareToggleLabel: 'แชร์ห้องสนทนานี้',
    shareToggleDescription: 'เมื่อเปิดใช้ ใครก็ตามที่มีลิงก์จะดูบทสนทนานี้ได้ แต่จะส่งข้อความหรือเข้าร่วมไม่ได้',
    shareEnabledToastLabel: 'แชร์ห้องสนทนานี้แล้ว',
    shareDisabledToastLabel: 'ปิดการแชร์แล้ว',
    shareRefreshButtonLabel: 'รีเฟรชลิงก์แชร์',
    shareRefreshedToastLabel: 'รีเฟรชลิงก์แชร์แล้ว',
    shareLinkCopyButtonLabel: 'คัดลอกลิงก์',
    shareLinkCopiedToastLabel: 'คัดลอกลิงก์แล้ว',
    shareErrorToastLabel: 'ไม่สามารถอัปเดตการแชร์ได้ โปรดลองอีกครั้ง',
  },
  vi: {
    menuItemLabel: 'Quan ly cuoc tro chuyen',
    pageTitle: 'Quan ly cuoc tro chuyen',
    backButtonLabel: 'Quay lai',
    languageSelectorTitle: 'Chọn ngôn ngữ đích',
    languageSelectorDescription: 'Chọn nhiều ngôn ngữ để dịch sang tất cả cùng lúc.',
    languageSelectorCloseLabel: 'Dong',
    languageSelectorSearchPlaceholder: 'Tim ngon ngu',
    languageSelectorSortLocaleLabel: 'A-Z',
    languageSelectorSortAlphabeticalLabel: 'EN A-Z',
    languageSelectorNoResultsLabel: 'Khong tim thay ngon ngu phu hop.',
    renameButtonLabel: 'Doi ten',
    renameDialogTitle: 'Doi ten cuoc tro chuyen',
    renameFieldLabel: 'Ten cuoc tro chuyen',
    renameFieldPlaceholder: 'Nhap ten cuoc tro chuyen.',
    renameCancelLabel: 'Huy',
    renameConfirmLabel: 'Luu',
    renamingLabel: 'Dang luu...',
    renameEmptyMessage: 'Vui long nhap ten cuoc tro chuyen.',
    renameSuccessToastLabel: 'Da cap nhat ten cuoc tro chuyen.',
    renameErrorToastLabel: 'Khong the cap nhat ten cuoc tro chuyen. Vui long thu lai.',
    defaultDisplayLanguageMenuItemLabel: 'Ngôn ngữ hiển thị mặc định',
    defaultDisplayLanguagePageTitle: 'Ngôn ngữ hiển thị mặc định',
    participantsMenuItemLabel: 'Người tham gia',
    participantsPageTitle: 'Người tham gia',
    participantsSelfLabel: 'Bạn',
    participantsLoadingLabel: 'Đang tải...',
    participantsErrorLabel: 'Không thể tải danh sách người tham gia.',
    participantsRetryLabel: 'Thử lại',
    participantsInviteButtonLabel: 'Mời',
    shareToggleLabel: 'Chia sẻ cuộc trò chuyện này',
    shareToggleDescription: 'Khi bật, bất kỳ ai có liên kết đều có thể xem cuộc trò chuyện này. Họ không thể gửi tin nhắn hoặc tham gia.',
    shareEnabledToastLabel: 'Cuộc trò chuyện này hiện đã được chia sẻ.',
    shareDisabledToastLabel: 'Đã tắt chia sẻ.',
    shareRefreshButtonLabel: 'Làm mới liên kết chia sẻ',
    shareRefreshedToastLabel: 'Đã làm mới liên kết chia sẻ.',
    shareLinkCopyButtonLabel: 'Sao chép liên kết',
    shareLinkCopiedToastLabel: 'Đã sao chép liên kết.',
    shareErrorToastLabel: 'Không thể cập nhật chia sẻ. Vui lòng thử lại.',
  },
} satisfies Record<LegalDocumentLocale, LivePhoneDemoRoomManagementCopy>

export function resolveLivePhoneDemoRoomManagementCopy(
  uiLocale: string,
): LivePhoneDemoRoomManagementCopy {
  const supportedLocale = resolveSupportedLocaleTag(uiLocale) ?? DEFAULT_LOCALE
  const resolvedLocale = resolveLegalDocumentLocale(supportedLocale)

  return ROOM_MANAGEMENT_COPY_BY_LOCALE[resolvedLocale] ?? ROOM_MANAGEMENT_COPY_BY_LOCALE.en
}
