import {
  DEFAULT_LOCALE,
  resolveLegalDocumentLocale,
  resolveSupportedLocaleTag,
  type LegalDocumentLocale,
} from '@/i18n/config'
import type { LivePhoneDemoFeedbackCategory } from '@/i18n/types'
export type { LivePhoneDemoFeedbackCategory } from '@/i18n/types'

export type LivePhoneDemoFeedbackCopy = {
  pageTitle: string
  feedbackMenuItemLabel: string
  composeTabLabel: string
  historyTabLabel: string
  backButtonLabel: string
  closeButtonLabel: string
  historyTitle: string
  historyDescription: string
  historyLoadingLabel: string
  historyEmptyLabel: string
  historyErrorMessage: string
  pendingReplyLabel: string
  meLabel: string
  teamLabel: string
  categoryLabel: string
  messageLabel: string
  messagePlaceholder: string
  emailLabel: string
  emailPlaceholder: string
  sendButtonLabel: string
  sendingButtonLabel: string
  successMessage: string
  errorMessage: string
  invalidEmailMessage: string
  messageTooShortMessage: string
  categoryLabels: Record<LivePhoneDemoFeedbackCategory, string>
}

const FEEDBACK_COPY_BY_LOCALE = {
  ko: {
    pageTitle: '피드백',
    feedbackMenuItemLabel: '피드백',
    composeTabLabel: '보내기',
    historyTabLabel: '내역',
    backButtonLabel: '뒤로가기',
    closeButtonLabel: '닫기',
    historyTitle: '내 문의 내역',
    historyDescription: '보낸 내용과 운영진 답변이 시간순으로 쌓입니다.',
    historyLoadingLabel: '문의 내역 불러오는 중...',
    historyEmptyLabel: '아직 보낸 문의가 없습니다.',
    historyErrorMessage: '문의 내역을 불러오지 못했습니다.',
    pendingReplyLabel: '운영진 답변 대기 중',
    meLabel: '나',
    teamLabel: '운영진',
    categoryLabel: '종류',
    messageLabel: '내용',
    messagePlaceholder: '어떤 점이 불편했는지, 어떤 기능이 필요하신지 자세히 적어주세요.',
    emailLabel: '답변받을 이메일',
    emailPlaceholder: '선택사항',
    sendButtonLabel: '보내기',
    sendingButtonLabel: '보내는 중...',
    successMessage: '운영진에게 전달되었습니다. 감사합니다.',
    errorMessage: '전송에 실패했습니다. 잠시 후 다시 시도해 주세요.',
    invalidEmailMessage: '올바른 이메일 주소를 입력해 주세요.',
    messageTooShortMessage: '내용은 최소 5자 이상 입력해 주세요.',
    categoryLabels: {
      feedback: '피드백',
      suggestion: '건의사항',
      inquiry: '문의',
    },
  },
  en: {
    pageTitle: 'Feedback',
    feedbackMenuItemLabel: 'Feedback',
    composeTabLabel: 'Write',
    historyTabLabel: 'History',
    backButtonLabel: 'Go back',
    closeButtonLabel: 'Close',
    historyTitle: 'My feedback history',
    historyDescription: 'Your messages and team replies appear here in order.',
    historyLoadingLabel: 'Loading your history...',
    historyEmptyLabel: 'No messages sent yet.',
    historyErrorMessage: 'Failed to load your feedback history.',
    pendingReplyLabel: 'Waiting for a team reply',
    meLabel: 'You',
    teamLabel: 'Team',
    categoryLabel: 'Type',
    messageLabel: 'Message',
    messagePlaceholder: 'Tell us what happened, what you want improved, or what you need help with.',
    emailLabel: 'Reply email',
    emailPlaceholder: 'Optional',
    sendButtonLabel: 'Send',
    sendingButtonLabel: 'Sending...',
    successMessage: 'Your message was sent to the team.',
    errorMessage: 'Failed to send your message. Please try again.',
    invalidEmailMessage: 'Please enter a valid email address.',
    messageTooShortMessage: 'Please enter at least 5 characters.',
    categoryLabels: {
      feedback: 'Feedback',
      suggestion: 'Suggestion',
      inquiry: 'Inquiry',
    },
  },
  ja: {
    pageTitle: 'フィードバック',
    feedbackMenuItemLabel: 'フィードバック',
    composeTabLabel: '送信',
    historyTabLabel: '履歴',
    backButtonLabel: '戻る',
    closeButtonLabel: '閉じる',
    historyTitle: 'お問い合わせ履歴',
    historyDescription: '送信した内容と運営チームからの返信が時系列で表示されます。',
    historyLoadingLabel: '履歴を読み込み中...',
    historyEmptyLabel: 'まだ送信したメッセージはありません。',
    historyErrorMessage: '履歴を読み込めませんでした。',
    pendingReplyLabel: 'チームからの返信待ち',
    meLabel: '自分',
    teamLabel: '運営',
    categoryLabel: '種類',
    messageLabel: '内容',
    messagePlaceholder: '不便だった点、改善してほしい点、サポートが必要な内容を詳しく入力してください。',
    emailLabel: '返信用メール',
    emailPlaceholder: '任意',
    sendButtonLabel: '送信',
    sendingButtonLabel: '送信中...',
    successMessage: '運営チームに送信しました。',
    errorMessage: '送信に失敗しました。しばらくしてからもう一度お試しください。',
    invalidEmailMessage: '有効なメールアドレスを入力してください。',
    messageTooShortMessage: '5文字以上入力してください。',
    categoryLabels: {
      feedback: 'フィードバック',
      suggestion: '提案',
      inquiry: 'お問い合わせ',
    },
  },
  'zh-CN': {
    pageTitle: '反馈',
    feedbackMenuItemLabel: '反馈',
    composeTabLabel: '发送',
    historyTabLabel: '记录',
    backButtonLabel: '返回',
    closeButtonLabel: '关闭',
    historyTitle: '我的反馈记录',
    historyDescription: '您发送的内容和运营团队的回复会按时间顺序显示。',
    historyLoadingLabel: '正在加载反馈记录...',
    historyEmptyLabel: '您还没有发送任何反馈。',
    historyErrorMessage: '无法加载反馈记录。',
    pendingReplyLabel: '等待团队回复',
    meLabel: '我',
    teamLabel: '运营团队',
    categoryLabel: '类型',
    messageLabel: '内容',
    messagePlaceholder: '请详细说明遇到的问题、希望改进的地方，或您需要帮助的内容。',
    emailLabel: '回复邮箱',
    emailPlaceholder: '选填',
    sendButtonLabel: '发送',
    sendingButtonLabel: '发送中...',
    successMessage: '已发送给运营团队。',
    errorMessage: '发送失败，请稍后再试。',
    invalidEmailMessage: '请输入有效的邮箱地址。',
    messageTooShortMessage: '请至少输入 5 个字符。',
    categoryLabels: {
      feedback: '反馈',
      suggestion: '建议',
      inquiry: '咨询',
    },
  },
  'zh-TW': {
    pageTitle: '回饋',
    feedbackMenuItemLabel: '回饋',
    composeTabLabel: '送出',
    historyTabLabel: '紀錄',
    backButtonLabel: '返回',
    closeButtonLabel: '關閉',
    historyTitle: '我的回饋紀錄',
    historyDescription: '您送出的內容與營運團隊的回覆會依時間順序顯示。',
    historyLoadingLabel: '正在載入回饋紀錄...',
    historyEmptyLabel: '您還沒有送出任何回饋。',
    historyErrorMessage: '無法載入回饋紀錄。',
    pendingReplyLabel: '等待團隊回覆',
    meLabel: '我',
    teamLabel: '營運團隊',
    categoryLabel: '類型',
    messageLabel: '內容',
    messagePlaceholder: '請詳細說明遇到的問題、希望改善的地方，或您需要協助的內容。',
    emailLabel: '回覆信箱',
    emailPlaceholder: '選填',
    sendButtonLabel: '送出',
    sendingButtonLabel: '送出中...',
    successMessage: '已送出給營運團隊。',
    errorMessage: '送出失敗，請稍後再試。',
    invalidEmailMessage: '請輸入有效的電子郵件地址。',
    messageTooShortMessage: '請至少輸入 5 個字元。',
    categoryLabels: {
      feedback: '回饋',
      suggestion: '建議',
      inquiry: '詢問',
    },
  },
  fr: {
    pageTitle: 'Retour',
    feedbackMenuItemLabel: 'Retour',
    composeTabLabel: 'Écrire',
    historyTabLabel: 'Historique',
    backButtonLabel: 'Retour',
    closeButtonLabel: 'Fermer',
    historyTitle: 'Mon historique',
    historyDescription: "Vos messages et les réponses de l'équipe s'affichent dans l'ordre chronologique.",
    historyLoadingLabel: 'Chargement de vos messages...',
    historyEmptyLabel: "Vous n'avez encore envoyé aucun message.",
    historyErrorMessage: "Impossible de charger votre historique.",
    pendingReplyLabel: "En attente d'une réponse",
    meLabel: 'Moi',
    teamLabel: 'Équipe',
    categoryLabel: 'Type',
    messageLabel: 'Message',
    messagePlaceholder: "Expliquez ce qui s'est passé, ce que vous voudriez voir amélioré, ou l'aide dont vous avez besoin.",
    emailLabel: 'E-mail de réponse',
    emailPlaceholder: 'Facultatif',
    sendButtonLabel: 'Envoyer',
    sendingButtonLabel: 'Envoi...',
    successMessage: "Votre message a été envoyé à l'équipe.",
    errorMessage: "Échec de l'envoi du message. Veuillez réessayer plus tard.",
    invalidEmailMessage: 'Veuillez saisir une adresse e-mail valide.',
    messageTooShortMessage: 'Veuillez saisir au moins 5 caractères.',
    categoryLabels: {
      feedback: 'Retour',
      suggestion: 'Suggestion',
      inquiry: 'Question',
    },
  },
  de: {
    pageTitle: 'Feedback',
    feedbackMenuItemLabel: 'Feedback',
    composeTabLabel: 'Schreiben',
    historyTabLabel: 'Verlauf',
    backButtonLabel: 'Zurück',
    closeButtonLabel: 'Schließen',
    historyTitle: 'Mein Verlauf',
    historyDescription: 'Ihre Nachrichten und Antworten des Teams werden in zeitlicher Reihenfolge angezeigt.',
    historyLoadingLabel: 'Verlauf wird geladen...',
    historyEmptyLabel: 'Sie haben noch keine Nachricht gesendet.',
    historyErrorMessage: 'Der Verlauf konnte nicht geladen werden.',
    pendingReplyLabel: 'Warten auf Antwort',
    meLabel: 'Ich',
    teamLabel: 'Team',
    categoryLabel: 'Typ',
    messageLabel: 'Nachricht',
    messagePlaceholder: 'Beschreiben Sie bitte genau, was passiert ist, was verbessert werden sollte oder wobei Sie Hilfe brauchen.',
    emailLabel: 'Antwort-E-Mail',
    emailPlaceholder: 'Optional',
    sendButtonLabel: 'Senden',
    sendingButtonLabel: 'Wird gesendet...',
    successMessage: 'Ihre Nachricht wurde an das Team gesendet.',
    errorMessage: 'Ihre Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es später erneut.',
    invalidEmailMessage: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    messageTooShortMessage: 'Bitte geben Sie mindestens 5 Zeichen ein.',
    categoryLabels: {
      feedback: 'Feedback',
      suggestion: 'Vorschlag',
      inquiry: 'Anfrage',
    },
  },
  es: {
    pageTitle: 'Comentarios',
    feedbackMenuItemLabel: 'Comentarios',
    composeTabLabel: 'Escribir',
    historyTabLabel: 'Historial',
    backButtonLabel: 'Volver',
    closeButtonLabel: 'Cerrar',
    historyTitle: 'Mi historial',
    historyDescription: 'Tus mensajes y las respuestas del equipo aparecen en orden.',
    historyLoadingLabel: 'Cargando tu historial...',
    historyEmptyLabel: 'Aún no has enviado ningún mensaje.',
    historyErrorMessage: 'No se pudo cargar tu historial.',
    pendingReplyLabel: 'Esperando respuesta del equipo',
    meLabel: 'Yo',
    teamLabel: 'Equipo',
    categoryLabel: 'Tipo',
    messageLabel: 'Mensaje',
    messagePlaceholder: 'Cuéntanos qué pasó, qué te gustaría mejorar o con qué necesitas ayuda.',
    emailLabel: 'Correo de respuesta',
    emailPlaceholder: 'Opcional',
    sendButtonLabel: 'Enviar',
    sendingButtonLabel: 'Enviando...',
    successMessage: 'Tu mensaje se envió al equipo.',
    errorMessage: 'No se pudo enviar tu mensaje. Inténtalo de nuevo más tarde.',
    invalidEmailMessage: 'Introduce una dirección de correo válida.',
    messageTooShortMessage: 'Introduce al menos 5 caracteres.',
    categoryLabels: {
      feedback: 'Comentario',
      suggestion: 'Sugerencia',
      inquiry: 'Consulta',
    },
  },
  pt: {
    pageTitle: 'Feedback',
    feedbackMenuItemLabel: 'Feedback',
    composeTabLabel: 'Escrever',
    historyTabLabel: 'Histórico',
    backButtonLabel: 'Voltar',
    closeButtonLabel: 'Fechar',
    historyTitle: 'Meu histórico',
    historyDescription: 'Suas mensagens e as respostas da equipe aparecem em ordem cronológica.',
    historyLoadingLabel: 'Carregando seu histórico...',
    historyEmptyLabel: 'Você ainda não enviou nenhuma mensagem.',
    historyErrorMessage: 'Não foi possível carregar seu histórico.',
    pendingReplyLabel: 'Aguardando resposta da equipe',
    meLabel: 'Eu',
    teamLabel: 'Equipe',
    categoryLabel: 'Tipo',
    messageLabel: 'Mensagem',
    messagePlaceholder: 'Conte o que aconteceu, o que você quer melhorar ou com o que precisa de ajuda.',
    emailLabel: 'E-mail para resposta',
    emailPlaceholder: 'Opcional',
    sendButtonLabel: 'Enviar',
    sendingButtonLabel: 'Enviando...',
    successMessage: 'Sua mensagem foi enviada para a equipe.',
    errorMessage: 'Não foi possível enviar sua mensagem. Tente novamente mais tarde.',
    invalidEmailMessage: 'Digite um endereço de e-mail válido.',
    messageTooShortMessage: 'Digite pelo menos 5 caracteres.',
    categoryLabels: {
      feedback: 'Feedback',
      suggestion: 'Sugestão',
      inquiry: 'Dúvida',
    },
  },
  it: {
    pageTitle: 'Feedback',
    feedbackMenuItemLabel: 'Feedback',
    composeTabLabel: 'Scrivi',
    historyTabLabel: 'Cronologia',
    backButtonLabel: 'Indietro',
    closeButtonLabel: 'Chiudi',
    historyTitle: 'La mia cronologia',
    historyDescription: 'I tuoi messaggi e le risposte del team compaiono in ordine cronologico.',
    historyLoadingLabel: 'Caricamento della cronologia...',
    historyEmptyLabel: 'Non hai ancora inviato alcun messaggio.',
    historyErrorMessage: 'Impossibile caricare la cronologia.',
    pendingReplyLabel: 'In attesa di una risposta',
    meLabel: 'Io',
    teamLabel: 'Team',
    categoryLabel: 'Tipo',
    messageLabel: 'Messaggio',
    messagePlaceholder: 'Descrivi cosa è successo, cosa vorresti migliorare o in cosa hai bisogno di aiuto.',
    emailLabel: 'E-mail per la risposta',
    emailPlaceholder: 'Facoltativo',
    sendButtonLabel: 'Invia',
    sendingButtonLabel: 'Invio in corso...',
    successMessage: 'Il tuo messaggio è stato inviato al team.',
    errorMessage: 'Invio del messaggio non riuscito. Riprova più tardi.',
    invalidEmailMessage: 'Inserisci un indirizzo e-mail valido.',
    messageTooShortMessage: 'Inserisci almeno 5 caratteri.',
    categoryLabels: {
      feedback: 'Feedback',
      suggestion: 'Suggerimento',
      inquiry: 'Domanda',
    },
  },
  ru: {
    pageTitle: 'Обратная связь',
    feedbackMenuItemLabel: 'Обратная связь',
    composeTabLabel: 'Написать',
    historyTabLabel: 'История',
    backButtonLabel: 'Назад',
    closeButtonLabel: 'Закрыть',
    historyTitle: 'Моя история',
    historyDescription: 'Ваши сообщения и ответы команды отображаются по порядку.',
    historyLoadingLabel: 'Загрузка истории...',
    historyEmptyLabel: 'Вы еще не отправляли сообщения.',
    historyErrorMessage: 'Не удалось загрузить историю.',
    pendingReplyLabel: 'Ожидает ответа команды',
    meLabel: 'Я',
    teamLabel: 'Команда',
    categoryLabel: 'Тип',
    messageLabel: 'Сообщение',
    messagePlaceholder: 'Расскажите, что произошло, что вы хотите улучшить или с чем вам нужна помощь.',
    emailLabel: 'E-mail для ответа',
    emailPlaceholder: 'Необязательно',
    sendButtonLabel: 'Отправить',
    sendingButtonLabel: 'Отправка...',
    successMessage: 'Ваше сообщение отправлено команде.',
    errorMessage: 'Не удалось отправить сообщение. Попробуйте позже.',
    invalidEmailMessage: 'Введите корректный адрес электронной почты.',
    messageTooShortMessage: 'Введите не менее 5 символов.',
    categoryLabels: {
      feedback: 'Отзыв',
      suggestion: 'Предложение',
      inquiry: 'Вопрос',
    },
  },
  ar: {
    pageTitle: 'الملاحظات',
    feedbackMenuItemLabel: 'الملاحظات',
    composeTabLabel: 'كتابة',
    historyTabLabel: 'السجل',
    backButtonLabel: 'رجوع',
    closeButtonLabel: 'إغلاق',
    historyTitle: 'سجل رسائلي',
    historyDescription: 'تظهر رسائلك وردود الفريق بالترتيب الزمني.',
    historyLoadingLabel: 'جار تحميل السجل...',
    historyEmptyLabel: 'لم ترسل أي رسالة بعد.',
    historyErrorMessage: 'تعذر تحميل السجل.',
    pendingReplyLabel: 'بانتظار رد الفريق',
    meLabel: 'أنا',
    teamLabel: 'الفريق',
    categoryLabel: 'النوع',
    messageLabel: 'الرسالة',
    messagePlaceholder: 'أخبرنا بما حدث أو ما الذي تريد تحسينه أو ما الذي تحتاج إلى مساعدة بشأنه.',
    emailLabel: 'بريد الرد',
    emailPlaceholder: 'اختياري',
    sendButtonLabel: 'إرسال',
    sendingButtonLabel: 'جار الإرسال...',
    successMessage: 'تم إرسال رسالتك إلى الفريق.',
    errorMessage: 'تعذر إرسال رسالتك. يرجى المحاولة لاحقًا.',
    invalidEmailMessage: 'يرجى إدخال بريد إلكتروني صالح.',
    messageTooShortMessage: 'يرجى إدخال 5 أحرف على الأقل.',
    categoryLabels: {
      feedback: 'ملاحظات',
      suggestion: 'اقتراح',
      inquiry: 'استفسار',
    },
  },
  hi: {
    pageTitle: 'फ़ीडबैक',
    feedbackMenuItemLabel: 'फ़ीडबैक',
    composeTabLabel: 'लिखें',
    historyTabLabel: 'इतिहास',
    backButtonLabel: 'वापस',
    closeButtonLabel: 'बंद करें',
    historyTitle: 'मेरा इतिहास',
    historyDescription: 'आपके संदेश और टीम के जवाब क्रम से यहां दिखेंगे।',
    historyLoadingLabel: 'इतिहास लोड हो रहा है...',
    historyEmptyLabel: 'आपने अभी तक कोई संदेश नहीं भेजा है।',
    historyErrorMessage: 'इतिहास लोड नहीं हो सका।',
    pendingReplyLabel: 'टीम के जवाब की प्रतीक्षा में',
    meLabel: 'मैं',
    teamLabel: 'टीम',
    categoryLabel: 'प्रकार',
    messageLabel: 'संदेश',
    messagePlaceholder: 'बताइए क्या हुआ, आप क्या बेहतर चाहते हैं, या आपको किस बात में मदद चाहिए।',
    emailLabel: 'जवाबी ईमेल',
    emailPlaceholder: 'वैकल्पिक',
    sendButtonLabel: 'भेजें',
    sendingButtonLabel: 'भेजा जा रहा है...',
    successMessage: 'आपका संदेश टीम को भेज दिया गया है।',
    errorMessage: 'आपका संदेश भेजा नहीं जा सका। कृपया बाद में फिर कोशिश करें।',
    invalidEmailMessage: 'कृपया मान्य ईमेल पता दर्ज करें।',
    messageTooShortMessage: 'कृपया कम से कम 5 अक्षर दर्ज करें।',
    categoryLabels: {
      feedback: 'फ़ीडबैक',
      suggestion: 'सुझाव',
      inquiry: 'पूछताछ',
    },
  },
  th: {
    pageTitle: 'ข้อเสนอแนะ',
    feedbackMenuItemLabel: 'ข้อเสนอแนะ',
    composeTabLabel: 'เขียน',
    historyTabLabel: 'ประวัติ',
    backButtonLabel: 'ย้อนกลับ',
    closeButtonLabel: 'ปิด',
    historyTitle: 'ประวัติของฉัน',
    historyDescription: 'ข้อความของคุณและคำตอบจากทีมจะแสดงตามลำดับเวลา',
    historyLoadingLabel: 'กำลังโหลดประวัติ...',
    historyEmptyLabel: 'คุณยังไม่ได้ส่งข้อความ',
    historyErrorMessage: 'ไม่สามารถโหลดประวัติได้',
    pendingReplyLabel: 'กำลังรอคำตอบจากทีม',
    meLabel: 'ฉัน',
    teamLabel: 'ทีมงาน',
    categoryLabel: 'ประเภท',
    messageLabel: 'ข้อความ',
    messagePlaceholder: 'บอกเราว่าเกิดอะไรขึ้น อยากให้ปรับปรุงอะไร หรือคุณต้องการความช่วยเหลือเรื่องใด',
    emailLabel: 'อีเมลสำหรับติดต่อกลับ',
    emailPlaceholder: 'ไม่บังคับ',
    sendButtonLabel: 'ส่ง',
    sendingButtonLabel: 'กำลังส่ง...',
    successMessage: 'ส่งข้อความถึงทีมงานแล้ว',
    errorMessage: 'ส่งข้อความไม่สำเร็จ กรุณาลองใหม่ภายหลัง',
    invalidEmailMessage: 'กรุณากรอกอีเมลที่ถูกต้อง',
    messageTooShortMessage: 'กรุณากรอกอย่างน้อย 5 ตัวอักษร',
    categoryLabels: {
      feedback: 'ข้อเสนอแนะ',
      suggestion: 'คำแนะนำ',
      inquiry: 'สอบถาม',
    },
  },
  vi: {
    pageTitle: 'Phản hồi',
    feedbackMenuItemLabel: 'Phản hồi',
    composeTabLabel: 'Viết',
    historyTabLabel: 'Lịch sử',
    backButtonLabel: 'Quay lại',
    closeButtonLabel: 'Đóng',
    historyTitle: 'Lịch sử của tôi',
    historyDescription: 'Tin nhắn của bạn và phản hồi từ đội ngũ sẽ hiển thị theo thứ tự thời gian.',
    historyLoadingLabel: 'Đang tải lịch sử...',
    historyEmptyLabel: 'Bạn chưa gửi tin nhắn nào.',
    historyErrorMessage: 'Không thể tải lịch sử phản hồi.',
    pendingReplyLabel: 'Đang chờ đội ngũ phản hồi',
    meLabel: 'Tôi',
    teamLabel: 'Đội ngũ',
    categoryLabel: 'Loại',
    messageLabel: 'Tin nhắn',
    messagePlaceholder: 'Hãy cho chúng tôi biết điều gì đã xảy ra, bạn muốn cải thiện điều gì, hoặc bạn cần hỗ trợ gì.',
    emailLabel: 'Email phản hồi',
    emailPlaceholder: 'Tùy chọn',
    sendButtonLabel: 'Gửi',
    sendingButtonLabel: 'Đang gửi...',
    successMessage: 'Tin nhắn của bạn đã được gửi đến đội ngũ.',
    errorMessage: 'Không thể gửi tin nhắn. Vui lòng thử lại sau.',
    invalidEmailMessage: 'Vui lòng nhập địa chỉ email hợp lệ.',
    messageTooShortMessage: 'Vui lòng nhập ít nhất 5 ký tự.',
    categoryLabels: {
      feedback: 'Phản hồi',
      suggestion: 'Đề xuất',
      inquiry: 'Hỏi đáp',
    },
  },
} satisfies Record<LegalDocumentLocale, LivePhoneDemoFeedbackCopy>

export function resolveLivePhoneDemoFeedbackCopy(
  uiLocale: string,
): LivePhoneDemoFeedbackCopy {
  const supportedLocale = resolveSupportedLocaleTag(uiLocale) ?? DEFAULT_LOCALE
  const resolvedLocale = resolveLegalDocumentLocale(supportedLocale)

  return FEEDBACK_COPY_BY_LOCALE[resolvedLocale] ?? FEEDBACK_COPY_BY_LOCALE.en
}
